### ISSUE TITLE
Support a try_read_message on WebSocket

### ISSUE THREAD

**Issue by rtyler** [snapview/tungstenite-rs#103]
Unlike some previous issues, such as #11, I'm most interested in a `try_read_message` which would return a message if were available.

I don't have another need to work with the underlying streams, so the existing abstraction in `tungstenite::protocol::WebSocket` is already sufficient. I simply want to attempt to pull a message out of the WebSocket for processing unless one exists.

My immediate use-case is a simple command line interactive loop

**Comment by agalakhov** [comment]
Do you mean taking message out of the Tungstenite internal buffer without trying to read it from the stream?

**Comment by rtyler** [comment]
@agalakhov Perhaps! I'm not too familiar with what's happening underneath the covers, but I do know that sometimes a message is available and `read_message` returns immediately, and sometimes it will wait until the server sends another message along.

What I would like from a `try_read_message` would be for the second case, where a message is not available immediately, to just return.

**Comment by redblobgames** [comment]
I'm currently setting a read_timeout on the stream for this. If there's no message, read_message() will return `Err(tungstenite::Error::Io(ref e)` where `e.kind() == std::io::ErrorKind::WouldBlock`. It's good enough for my needs (toy example) but I don't know if this is guaranteed to work in all cases.

**Comment by agalakhov** [comment]
@rtyler It's not that simple. There are two buffers, one in Tungstenite and one in the OS. While tue Thunstenite one _may_ contain a message, it is unlikely and only happens if messages are small and arrive in groups. If there is a message in the OS buffer or in the buffer of underlying stream (if any), the _only_ way to query it is to call blocking read. It is impossible to support `try_read_message` in `WebSocket` unless there is `try_read` in the stream, and `TcpStream` does not have any `try_read` method.

Possible solutions are:
* Switch the stream to non-blocking mode using `set_nonblocking()`. The underlying stream is accessible using `get_mut()`. After that, every `read_message()` will act like `try_read_message()` returning error with `WouldBlock` error kind if there is no message. If you need to wait, use `mio`.
* Use `tokio-tungstenite` and futures to fetch messages asynchronously.
* Set timeout to some small value. This would work but is probably less efficient.

@redblobgames You'll get exactly the same effect by calling `set_nonblocking`. This would be more efficient since `read_message` will always finish immediately without any timeout, thus improving overall latency. You still need to wait somewhere to avoid 100% CPU consumption, but you can then do this using `mio`. In fact, `set_nonblocking` is a equivalent of `set_timeout(0)`.
