### ISSUE TITLE
Failed: Url("TLS support not compiled in.")

### ISSUE THREAD

**Issue by andrii-blaize** [snapview/tungstenite-rs#109]
Every time get this message :

![image](https://user-images.githubusercontent.com/59236907/76146032-07c70380-6098-11ea-96e4-38dbfc666ab5.png)

I checked impl of client and see that it throw it when feature is not enabled.
But 

 
![image](https://user-images.githubusercontent.com/59236907/76146048-380ea200-6098-11ea-94fe-c21221c41459.png)

Need some explanation what I doing wrong. Thanks!

**Comment by agalakhov** [comment]
Why you're including `tungstenite` while using `tokio-tungstenite`? You set features for the wrong crate. Yo even include the wrong crate.

And please do not post screenshots. Lucky you, you did not cut the screenshot good enough so that the line causing the error is visible by accident. From the information you intended to post it were impossible to say what you're doing wrong.

**Comment by application-developer-DA** [comment]
Sorry, but I'm going to close this issue as it seems that there was not enough information to investigate the issue and there were no response.

This definitely seems more like a technical question rather than a bug or a problem with `tungstenite-rs` and/or `tokio-tungstnite`.

If I'm mistaken, please update the description / describe your problem and re-open the issue, so that we can check it on our side as well.
