### ISSUE TITLE
Calling tungstenite ws from rocket route

### ISSUE THREAD

**Issue by hyousef-rusty** [snapview/tungstenite-rs#124]
I've 2 main routes in my rocket.rs app:

```rust
#[get("/route1")]
fn route1() -> Template {}

#[get("/route2")]
fn route2() -> Template {}
```

And I want to use `ws` so that from each route I can send msg for all connected and opened sockets, I opened issue [#122](https://github.com/snapview/tungstenite-rs/issues/122#issue-620529844) to understand how to send to all opened connections, here I want to understand how to send the msg from the 2 routes!

**Comment by application-developer-DA** [comment]
> so that from each route I can send msg for all connected and opened sockets

What do you mean to all connected and opened sockets? To all open web-socket connections, handled by `tungstenite`? Well, this is fairly simple, but you need to store this connections when you accept them in some sort of `HashMap` or any other container which suits your tasks, then you just iterate over the stored connections and send a message.

I.e. at [that point](https://github.com/snapview/tungstenite-rs/blob/master/examples/server.rs#L27) you can just store the `websocket` somewhere, so that you can use it at a place you want to send a message from.
