### ISSUE TITLE
Cannot connect via `wss`

### ISSUE THREAD

**Issue by robertsteilberg** [snapview/tungstenite-rs#137]
I'm trying to follow `examples/client.rs` and connect to a server via `wss`:

```
let resp = connect(Url::parse("wss://localhost:433/aircraft/").unwrap());
```
I have
```
tungstenite = {version = "^0.11.1", features = ["tls"]}
```
in my Cargo.toml file. However, no matter what I try, tungstenite is unable to connect to the URL. I've verified that other WebSocket clients can connect to my server over `wss` at this URL so I do not believe it is a server issue. Am I missing something here?

**Comment by application-developer-DA** [comment]
It would be useful if you could provide an error that you receive when trying to connect ;)

**Comment by robertsteilberg** [comment]
The error I get is `URL Error: Cannot connect to wss://localhost:433/aircraft/`

I dig into the source code and I want to try to debug it myself, but I'm not sure how to edit crates locally. Sadly, I come from Node land.

**Comment by najamelan** [comment]
I think ssl requires a fully qualified domain name, which localhost is not. I would try adding a domain name to your hosts file and then generating a valid certificate for that domain. 

There are also ssl libs in rust that allow you to ignore the certificate, but then you wouldn't use the connect method from tungstenite but rather establish the connection first and then pass it to tungstenite, so that is a different workflow.

That being said, the error message is not helpful.

**Comment by robertsteilberg** [comment]
Is that an ssl requirement or a tungstenite requirement? Because I can use a regular 'ol Chrome WebSocket client web extension with `wss://localhost:433/aircraft/` and it works just fine.

**Comment by najamelan** [comment]
I'm sorry, my memory is a bit foggy, but I remember I struggled a bit to get ssl working, and we regularly see issues about that here because others are as well. I just wonder if you connect from chrome, what certificate do you use to validate "localhost"? Do they have  a hardcoded exception for localhost? 

I just remember that in order for it to work for me I had to generate a proper certificate and I think I used a fqdn for that.

**Comment by robertsteilberg** [comment]
Took me this long, but you were correct. I got a named cert finally and was able to connect to a WebSocket server via `wss` in tungstenite. Thanks!
