### ISSUE TITLE
What is status of this library?

### ISSUE THREAD

**Issue by vi** [snapview/tungstenite-rs#157]
README states:

> This library is a work in progress. Feel free to ask questions and send us pull requests.

Does this "work in progress" mean "it's not ready for real use yet" or "more features are still to be added"?

Maybe Tungstenie can already be considered the primary Websocket library for Rust?

**Comment by application-developer-DA** [comment]
> Does this "work in progress" mean "it's not ready for real use yet" or "more features are still to be added"?

I think it's the latter one :) Perhaps README must be updated to now confuse people (we've actually have been actively using both `tungstenite` and `tokio-tungstenite` in production). We've always tried to make sure that `tungstenite` is stable and robust and does not exhibit any bugs, thus we've always fixed each issue that was classified as bug with the highest priority making sure that all open issues in our repositories are enhancements / improvements rather than actual problems or bugs. This is actually one of the reasons why we're sometimes too pedantic when checking the PRs and do not merge them if there are any issue or possible side effects or some sort of uncertainty.
