### ISSUE TITLE
Handling "pong" messages

### ISSUE THREAD

**Issue by alexcrichton** [snapview/tungstenite-rs#16]
Hello! I was tinkering around and wondering how to implement a timeout of a pong message. That is, after a ping is sent, having a maximum amount of time before the pong is received after which the connection is torn down. It looks like right now though once a pong message is received currently [no action is taken](https://github.com/snapview/tungstenite-rs/blob/9d6c3058d5dadbf3be86b8cb16d9da0b4e401a00/src/protocol/mod.rs#L367-L375). 

I was wondering, is there perhaps another method to currently implement this? If not, do y'all have thoughts on how this might be implemented?

**Comment by agalakhov** [comment]
Hello! The RFC does not document what to do in case of missing pong. And it explicitly allows sending a pong without ping. So that's what we don't track pings now.

From my experience, the websocket ping is needed to avoid TCP timeouts if no useful information is being sent. The TCP socket itself handles network timeouts just fine, and the action is taken by the OS and not by us. Is there any reason tracking ping timeouts at application level?

**Comment by agalakhov** [comment]
A possible solution is: we add a timeout parameter to the `send_ping()` call. And we return an `Err(PingTimeout)` from `read_message()` if timeout is reached. The user can ignore this message and call `read_message()` again. If the underlying socket blocks, we return this value as soon as it unblocks. If the underlying socket is a non-blocking one, i.e. from Tokio, we return the value as soon as we encounter a timeout. The corresponding future can take care of that, but we have to give it the access to the pong deadline value. It is enough to store just one (earliest) value since the RFC allows to reply to many pings with a single pong.

**Comment by alexcrichton** [comment]
Oh yeah I actually wouldn't really expect the core libary to do anything by default when handling pong messages, I think the current implementation seems correct by just ignoring pongs. What I'm thinking though is that an application-specific usage of websockets might do something different, e.g. using ping/pong latency as a test of whether the client is even still connected at all. 

All I'd be looking for here is the ability for an application to react in a custom way to a pong message coming in. This may want to one day be a default option for convenience in tungstenite or tokio-tungstenite, but I figure that in the end having a custom handler for a pong sort of makes sense regardless.

An example of what I'm thinking is https://github.com/alexcrichton/tungstenite-rs/commit/7d1428085edb620df96527070aba55d9e64fb030 where the trait `CtlMessageHandler` represents various "callbacks" and that's passed in on each call to `read_message`. Alternatively something like that could also be stored directly in `WebSocket<T>` itself? I built on top of that in tokio-tungstenite to add https://github.com/alexcrichton/tokio-tungstenite/commit/f4a661efa5934a7563514ace1f40787ccd40da90 which adds `send_ping` (just the ability to send a ping message at all) and a `poll_pong` message. The `poll_pong` message allows a task to get notified once the pong comes in, and then you can otherwise arrange for a timeout between those events to tear down the connection.

Does that make sense? I'd be up for any implementation though! I'm not at all wed do the WIP commits :)

**Comment by agalakhov** [comment]
A good idea, thanks. Alternative solution would be returning (processed) control messages from `read_message()` (adding them to `enum Message`). I personally prefer returning values as it's more of the spirit of functional programming than having mutable variables. But yes, having a `Borrow<ControlMessageProcessor>` inside the `WebSocket` itself is also possible.

I'd like to add some kind of ping tracking anyway.

**Comment by application-developer-DA** [comment]
Hi Alex, glad to hear from your again.

The idea you suggested is indeed one of the approaches which we may implement, although I'm not sure I fully understood the need of `poll_pong` in tokio-tungstenite. Even if we went for a callback-based approach, it seems like `poll_pong` would not be necessary (but maybe I missed something) as `Stream::poll` implementation already reads the messages and in case if the pong message is received, it would call the corresponding callback function, thus notifying the "subscriber" about the received pong message, allowing the user (or the library, tokio-tungstenite) to decide what to do with that.

I also like the idea of extending `enum Message` which has just been menitoned by Alexey. This idea had been once discussed in one of the issues in tokio-tungstenite: https://github.com/snapview/tokio-tungstenite/issues/6 and we planned to implement it eventually. What's your opinion? Would it be sufficient to make tungstenite and tokio-tungstenite more versatile and extendable?

**Comment by alexcrichton** [comment]
Oh yeah that'd definitely make sense! I figured that it was specifically avoided to have ping/pong in the `Message` enum, but that'd also work perfectly for my use case!

**Comment by alexcrichton** [comment]
I've opened up https://github.com/snapview/tungstenite-rs/pull/17, although feedback would be greatly appreciated!
