### ISSUE TITLE
Disconnect Client if Server is not Responding

### ISSUE THREAD

**Issue by mdben1247** [snapview/tungstenite-rs#165]
We are trying to disconnect our client in case the server becomes unresponsive. We have a loop similar to this:
```
loop {
    let msg = socket.read_message();
    let receipt_time = Utc::now();
    match msg {
        Ok(Message::Text(_)) => {
            last_msg = receipt_time;
        },
        Ok(_) => (),
        Err(_) => {
            break;
        }
    }
    if (receipt_time - last_msg).num_seconds() > 60 {
        break;
    }
}
```
However, this doesn't work because if server stops responding then `read_message()` waits indefinitely, never returning. I guess something like `read_message()` with a timeout would be needed for that. Am I missing something, is there another way to accomplish this?

**Comment by application-developer-DA** [comment]
Your guess is correct, `read_message()` with timeout would do, but we don't provide such a function (and don't plan to introduce it in a near future), the reason is that you could use `tokio-tungstenite` which is like a version of `tungstenite` for [Tokio](https://tokio.rs/) which allows you doing such things quite easily. I would suggest taking a look into the [Tokio's documentation](https://tokio.rs/tokio/tutorial), it would probably take a couple hours to read through, but it's worth it. Once you understand the basics of Tokio, you could switch to `tokio-tungstenite` to implement the desired behavior. Hope this helps!
