### ISSUE TITLE
Upgrading tokio to 1.0

### ISSUE THREAD

**Issue by Owez** [snapview/tungstenite-rs#169]
Hi, I'm planning to use warp for a web project and it depends on this by proxy of `tokio-tungstenite`. I was wondering when this library is planning to upgrade to the newly-released tokio 1.0 as I think it's the main blocker currently

**Comment by dnaka91** [comment]
Just for reference, there is still `http` v0.2.2 that currently causes to have `bytes` 1.0 and 0.5 compiled in. But it seems they plan to release the bytes 1.0 update as v0.2.**3** so that should solve itself once they release due to the current dependency spec. That means cargo can auto-upgrade from 0.2.2 to 0.2.3 without another release of `tungstenite` required.

https://github.com/hyperium/http/pull/463
