### ISSUE TITLE
Does non-async Tungstenite support full duplex WebSockets?

### ISSUE THREAD

**Issue by vi** [snapview/tungstenite-rs#171]
Can I send WebSocket messages to `tungstenite::protocol::WebSocket` while waiting for incoming messages from the web socket from the other thread?

Typically there is some `split` method, giving a read half and write half, but I don't see it in Tungstenite.

**Comment by application-developer-DA** [comment]
Yes, it's is possible and you do not necessary need threads for that, check the https://github.com/snapview/tokio-tungstenite , it contains examples, which also make use of `split()` ;)

**Comment by vi** [comment]
What about **non-async** WebSockets?

**Comment by vi** [comment]
> If you're using a regular tungstenite-rs, you would have to switch it in a non-blocking mode and use different threads or mio for that, which probably is not that handy.

Shall documentation mention that it's not possible to have blocking full duplex WebSockets?

I'm trying to migrate [`rust-websocket`](https://github.com/websockets-rs/rust-websocket)'s examples to Tungstenite, and stumbled upon `split` in non-async client example. `rust-websocket` has split for `ws://`, but not for `wss://`.

**Comment by application-developer-DA** [comment]
Well, we mention in the [introduction](https://github.com/snapview/tungstenite-rs#introduction) that we support both blocking and non-blocking modes / sync and async and that the `mio` might be required in case of going the async way. A link to `tokio-tungstenite` would be useful though.

The one could use the `client()` function inside a look to simulate the behavior which I believe you are referring to as blocking full duplex WebSocket.

**Comment by vi** [comment]
`client` also results in a `tungstenite::protocol::WebSocket` without `split`. It only provides low-level control of establishment phase of a web socket, not using phase.

> we mention in the introduction that we support both blocking and non-blocking modes

There is such thing as blocking, but full-duplex connection. This requires multiple threads although.

Shall it be explicitly documented that such arrangement is _not_ supported by Tungstenite?

**Comment by application-developer-DA** [comment]
> client also results in a tungstenite::protocol::WebSocket without split. It only provides low-level control of establishment phase of a web socket, not using phase.

Yes, but you could do the split in the user code since the resulting `WebSocket` would be non-blocking (if used with the non-blocking stream), i.e. implement one of the following strategies:
1. Use `Arc<Mutex<WebSocketStream>>` from 2 threads, each of which tries to call read and write methods (that would fail immediately if the messsage not available, returning `EWOULDBLOCK`.
2. Create a thread which owns the `WebSocketStream` and reads and writes data in the loop there. Before the thread is created, create a corresponding channel, the `rx` part of which would be owned by the thread that owns `WebSocketStream` and the `tx` part is owned by the threads that do the sending and receiving.

But in both cases you do end with some sort of a runtime, i.e. a very inefficient version of  Tokio.


> Shall it be explicitly documented that such arrangement is not supported by Tungstenite?

We could include that, but I just did not want other people be confused by the full-duplex blocking connection as actually the "full-duplex blocking part" is strictly speaking not part of the library, the libraries which do allow this just implement some sort of a runtime inside of them, we don't do it in `tungstenite-rs`, only providing the WebSocket-related logic, so the runtime is up to the user.

`tokio-tungstenite` is basically the version of `tungstenite-rs` modified for the Tokio runtime.
