### ISSUE TITLE
Need example of how to create non blocking client

### ISSUE THREAD

**Issue by Sibz** [snapview/tungstenite-rs#179]
The docs state to use the client function if non-blocking client is needed.

I haven't been able to figure this out. I can create the TCP stream using `TcpStream::connect` but then no idea what to put as the `Req` parameter for the client function.

Is it possible to get an example on how to create a websocket using TcpStream?

Currently this gives `HTTP error: 400 Bad Request`

```rust
let stream = TcpStream::connect("server.com:443")?;
let socket = tungstenite::client("wss://server.com/path", stream)?;
```
but `let socket = tungstenite::connect("wss://server.com/path")?;` works fine.

**Comment by application-developer-DA** [comment]
Your initial assumptions about `TcpStream` are correct, but you can't use the blocking `TcpStream` from the `std` for that. Apart from that I see that you're trying to connect to the `wss` (WebSocket Secure) server using the plain TCP connection, that is not going to work. You need to use the `TlsStream` on top of the `TcpStream`.

I would suggest [taking a look at](https://github.com/snapview/tokio-tungstenite) `tokio-tungstenite` that we developed to solve these problems. Otherwise you would have to design your own "Tokio-like" framework on top of the non-blocking `TcpStream` and `TlsStream`, implementing the proper handling of `EWOULDBLOCK` etc (I think that might be a good exercise for learning purposes, but I'm not sure it's a good way to do things if you just want to develop a quick PoC that solves some typical web-related task or indeed some sophisticated production level code).

**Comment by Sibz** [comment]
Hi thanks for your reply.
I did mange this in the end, I'll leave this here for anyone else trying to get non block with TLS
```rust
let url = Url::parse("wss://my.server.com/ws")?;
let socket_address = // Just supporting single address atm
    url.socket_addrs(|| None)?
       .pop().expect("Unable to extract socket address"))?;
let connector = TlsConnector::new()?;
let stream = TcpStream::connect(socket_address)?;
let host = url.host()
              .expect("Unable to extract host"))?
              .to_string();
let connected_stream = connector.connect(host.as_str(), stream.try_clone()?)?;
let socket = tungstenite::client(url, connected_stream)?.0;
stream.set_nonblocking(true)?;
```

**Comment by Sibz** [comment]
In the end I stored my socket in an arc mutex option and implemented this try_read fn that returned either a message, none or an error.
The none was when the underlying error was `WouldBlock`
I did it this way so multiple threads could read from the socket, however I think it was unnecessary as I now only use one thread to read. But heres the code for prosperity.

If any one gets stuck and needs a hand, tag me in a reply.

```rust
type ArcMutexOptionSocket = Arc<Mutex<Option<WebSocket<TlsStream<TcpStream>>>>>;

    fn try_read(socket: &mut ArcMutexOptionSocket) -> Result<Option<Message>>
    {
        let mut guard = socket.lock().unwrap();
        let x = match guard.as_mut().unwrap().read_message()
        {
            Ok(m) => Ok(Some(m)),
            Err(e) =>
            {
                match &e
                {
                    tungstenite::Error::Io(ee) =>
                    {
                        match ee.kind()
                        {
                            std::io::ErrorKind::WouldBlock => Ok(None),
                            _ => Err(e)
                        }
                    }
                    _ => Err(e)
                }
            }
        }?;
        Ok(x)
    }
}
```

**Comment by strohel** [comment]
Thanks for sharing your findings, @Sibz.
