### ISSUE TITLE
Handling ungraceful disconnects

### ISSUE THREAD

**Issue by sssilver** [snapview/tungstenite-rs#201]
What's the proper way to handle a client that ungracefully disconnects from a Tungstenite server? It looks like the TCP connection is just held forever and no error is ever emitted.

**Comment by application-developer-DA** [comment]
Well, if the client has disconnected, then the underlying connection is closed (there is no way to read from/write to it), so the only meaningful thing that the one could do in this case is to drop the corresponding `WebSocket`.

For more information: https://docs.rs/tungstenite/0.13.0/tungstenite/error/enum.Error.html#variant.ConnectionClosed

**Comment by sssilver** [comment]
The issue is that it seems user code does not get any notice that the client has gone away. So this question is about how do you detect ungraceful disconnects in user code.

**Comment by application-developer-DA** [comment]
> The issue is that it seems user code does not get any notice that the client has gone away.

You mean the application running on the user side does not see that the connection has been closed? There are several possibilities why this might happen, but they are not related to `tungstenite-rs`.

> So this question is about how do you detect ungraceful disconnects in user code.

We read from and write to the socket. If such attempt fails or if we see that the socket has been already closed without the WebSocket closure procedures in the RFC, then we return an `Err` from the corresponding read/write function.

**Comment by sssilver** [comment]
> You mean the application running on the user side does not see that the connection has been closed?

No, I mean the application that uses the tungstenite-rs library and serves as a websocket server.

> We read from and write to the socket. If such attempt fails or if we see that the socket has been already closed without the WebSocket closure procedures in the RFC, then we return an `Err` from the corresponding read/write function.

Does this mean that if the peer has gone away ungracefully, we will not find out until we attempt to read or write a frame with that peer?

**Comment by agalakhov** [comment]
> Does this mean that if the peer has gone away ungracefully, we will not find out until we attempt to read or write a frame with that peer?

In general, yes. But this happens on TCP level, not on WebSocket level. In order to get status of TCP connection, we have to perform some activity on this connection. That is, call `select()`, `send()` or `recv()` system call. Not a concern in real world applications since a real world application listens for incoming messages all the time.

This also means that if the client just drops the connection without even sending TCP `FIN`&Co, we wouldn't notice anything at all until our `send()` timeouts. This is how TCP works. Timeouts are settable using the standard `setsockopt()` call on the underlying socket. If you need early disconnect detection, you have to do some data exchange all the time. If there are no meaningful data to exchange, just send pings. It does not matter if they're send by the client or by the server.

**Comment by sssilver** [comment]
Is https://docs.rs/tungstenite/0.13.0/tungstenite/enum.Message.html#variant.Ping the right message to send? Is there a recommended frequency?

**Comment by agalakhov** [comment]
Yes, it is. Empty payload is Ok.

There is no recommended frequency. It depends on your application. If you send often, you'll detect disconnect quickly, but there will be network traffic and your software will behave poorly in case of temporary network outage. If you send rarely, you'll detect disconnects slower but without any drawbacks. If you just want to clean up "forgotten" connections on the server side, something like once pro minute (or sometimes even once pro 10 minutes) will be fine. But if you're doing that on client side and want to show some disconnect dialog to the end user, then something like five seconds looks better.

Be sure to set correct socket timeouts too. Ping is more a "connection keeper" than a "problem detector", it's first purpose is to allow for using shorter timeouts without spurious disconnects due to the lack of data. It is quite unlikely to detect network problems on its own, it just generates some non-null traffic so that TCP algorithms can do their jobs.
