### ISSUE TITLE
Add feature flag to use webpki-roots instead of rustls-native-certs

### ISSUE THREAD

**Issue by lucacasonato** [snapview/tungstenite-rs#215]
This was changed in the last release.

**Comment by dnaka91** [comment]
That would be great to have back in, especially as `tokio-tungstenite` still uses `webpki-roots` so both will be compiled even though only one is used and unnecessarily increasing the build time.

Most importantly though, with `webpki-roots` I was able to build Docker images that use the special `scratch` image as base, meaning it will have the bare minimum included and there will be no native certs. So my project will crash on startup due to missing root certs.

I'd be happy to prepare the changes for this, if there is the interest to make a new release soon. Maybe with the feature flags changed to (idea stolen from `reqwest`):
- `rustls-tls-webpki-roots`
- `rustls-tls-native-roots`
- `rustls-tls-manual-roots` (this one probably not for now, but if needed could help to allow providing custom root certificates).

Also, would be interesting to know what's the motivation for this change in the first place. All I could gather from #205 was that `rustls-native-certs` is helpful for local development and if local system configuration is preferred. At least in my case that's not what I need and it would have been great to just handle it through feature flags instead of fully switching over.

**Comment by application-developer-DA** [comment]
> That would be great to have back in, especially as tokio-tungstenite still uses webpki-roots so both will be compiled even though only one is used and unnecessarily increasing the build time.

Ah, you're right. That would be indeed an unnecessary dependency.


> Also, would be interesting to know what's the motivation for this change in the first place. All I could gather from #205 was that `rustls-native-certs` is helpful for local development and if local system configuration is preferred. At least in my case that's not what I need and it would have been great to just handle it through feature flags instead of fully switching over.

Yeah, I think that `rustls-native-certs` should ideally be an option, allowing the user to choose between `webpki-roots` and `rustls-native-certs`. Both [seem to have some pros and cons](https://github.com/rustls/rustls-native-certs#should-i-use-this-or-webpki-roots).

> I'd be happy to prepare the changes for this, if there is the interest to make a new release soon. Maybe with the feature flags changed to (idea stolen from `reqwest`):

This actually sounds good!

**Comment by dnaka91** [comment]
@application-developer-DA I opened a PR with the required changes.
I created it as draft s I still have a few open questions and would like to resolve them first before I consider the PR ready for review (code wise).

**Comment by dnaka91** [comment]
With #217 merged this can be closed maybe?

**Comment by application-developer-DA** [comment]
Oh yeah, thanks for reminding!
