### ISSUE TITLE
option to allow invalid certs

### ISSUE THREAD

**Issue by dbregman** [snapview/tungstenite-rs#219]
#84 #218 were closed without explanation, so creating a new issue to track this. Do not close just because its a dup of another closed issue, as the others were not resolved. If the resolution is WONTFIX then say so, and state the rationale. 

Allowing invalid certs is not an uncommon scenario. There's a reason every other websockets lib I've used provides the option (libwebsocket, IXWebsocket, gorilla websocket, off the top of my head). Sometimes the user doesn't have control over the server. If a user requires it, forcing them to roll their own does not enhance security, it just wastes their time (and yours when they post the issue again). 

Maybe there's a better websockets lib out there for rust, but last time I checked tungstenite seemed to be the "flagship" websockets lib as far as I could tell.

**Comment by application-developer-DA** [comment]
The #218 was closed because it contained many irrelevant information and [non-technical] statements, not to mention that it was a continuation of another issue (#84) that had more context and suggestions (even some sample code). Given the tone that conversation began and the aforementioned factors our experience suggested us that such discussions are not particularly productive and do not facilitate any progress.

It's however true that #84 might have been closed without a good explanation, so I've just written a comment there for those ones who stumble across similar issue. Feel free [to check the comment](https://github.com/snapview/tungstenite-rs/issues/84#issuecomment-879016202) for the rationale.

**Comment by dbregman** [comment]
> The #218 was closed because it contained a decent amount of irrelevant information and [non-technical] statements, not to mention that it was a continuation of another issue (#84) that had more context and suggestions (even some sample code). Given the tone that conversation began and the aforementioned factors our experience suggested us that such discussions are not particularly productive and do not facilitate any progress.

Agree my tone wasn't perfect in my first issue. I was frustrated and disappointed in the lib making it so difficult to do something that I had a (reasonable, I would argue) expectation of being an easy 1-liner, combined with the consequences of that. The non technical info was there to illustrate the use case.

> It's however true that #84 might have been closed without a good explanation, so I've just written a comment there for those ones who stumble across a similar issue. Feel free [to check the comment](https://github.com/snapview/tungstenite-rs/issues/84#issuecomment-879016202) for the rationale.

I appreciate the explanation. The logic is sound, although the end result is tungstenite is out of step with other websockets libs. It is odd to support TLS, yet not support even the most basic options for it. If tungstenite is not meant to be a standalone lib, then I would say just go all the way and drop the existing TLS support. The current situation is an awkward middleground that will inevitably lead to more undesired feature requests.
