### ISSUE TITLE
Permanently frozen WebSock stream

### ISSUE THREAD

**Issue by wbogocki** [snapview/tungstenite-rs#225]
Hi! This issue is probably a bit unusual because I'm mid-debugging but please bear with me.

I'm investigating spontaneous freezes in a WS client app. Sometimes they would happen every day and other times after a week. So far I pinpointed the cause to be Tugstenite's `read_message()` function.

Here's a screenshot of part of the call stack from a live debugger during the freeze. It's just happened and I have not debugged any further yet:

![image](https://user-images.githubusercontent.com/8852258/126601806-ca31f1c6-83de-4576-8106-eadbddc55270.png)

It looks like it's stuck on reading from the TCP stream. The connection is to a 3rd party service and I'm guessing it might have died without closing the socket. I'd expect Tungstenite to report an error in this case instead of blocking forever.

I thought about setting a read timeout on the underlying stream as a possible workaround. I'm not sure if this might break any Tungstenite invariants but it seems unlikely as timeouts should just be treated as normal errors.

Please let me know if you need more information. I'll be keeping the debugger open for the time being.

I will report back when I have more. Cheers! =)

**Comment by application-developer-DA** [comment]
> It looks like it's stuck on reading from the TCP stream. The connection is to a 3rd party service and I'm guessing it might have died without closing the socket. I'd expect Tungstenite to report an error in this case instead of blocking forever.

Yes, the `tungstenite-rs` will report it once we get aware of this. If we get an error while reading or writing, we report it immediately. If the connection dies, in some cases it may take a decent amount of time before the error is "propagated" to the TCP layer so that we can spot the issue. There are keep alive timers and intervals in the OS that are quite high by default, so spotting a dead connection may take a considerable amount of time. If this is the case, `tungstenite-rs` can't really do anything about it.

So if it's the issue with the dead connections I may suggest either of these:
1. Adjust the TCP keepalive options on the underlying TCP socket.
2. Implement some logic on the application layer to kill the connection when it's e.g. inactive for a certain amount of time.
3. Update system configuration that is related to keepalive and TCP retransmission logic. If you're on linux these are: `net.ipv4.tcp_keepalive_intvl`, `net.ipv4.tcp_keepalive_probes`, `net.ipv4.tcp_keepalive_time` and probably even more important `net.ipv4.tcp_retries2`.

**Comment by wbogocki** [comment]
It helps. For now, I've used Rust's `TcpStream` and `TcpStream::set_read_timeout()` with a fairly wide value and created the Tungstenite wrapper from that stream. So far it's triggered once. This makes me suspicious because this should be the first time I see a timeout in the logs for this program.

Anyway, I hope it's fixed now and the default timeout was at fault. It might be a good idea to expose a way to set the timeout in Tungstenite directly or at least to make sure that it's no longer than the WS heartbeat would allow anyway. I think for now we can close this though =)

Thanks!

**Comment by application-developer-DA** [comment]
Ok cool! We don't really set any timeouts on top of the `TcpStream`, because strictly speaking `tungstenite-rs` accepts any `Read + Write` stream which may or may not be the `TcpStream`. Most uses come from `tokio-tungstenite` that passes the Tokio's streams to it, so we can't (and ideally should not) assume anything about the stream apart that it's just some `Read`able and `Write`able entity.

**Comment by WestXu** [comment]
> It helps. For now, I've used Rust's `TcpStream` and `TcpStream::set_read_timeout()` with a fairly wide value and created the Tungstenite wrapper from that stream. So far it's triggered once. This makes me suspicious because this should be the first time I see a timeout in the logs for this program.
> 
> Anyway, I hope it's fixed now and the default timeout was at fault. It might be a good idea to expose a way to set the timeout in Tungstenite directly or at least to make sure that it's no longer than the WS heartbeat would allow anyway. I think for now we can close this though =)
> 
> Thanks!

Hey I encountered the same issue and am not sure to introduce a framework as big as tokio to fix this little thing. Could you share a bit code snippets of the wrapped instantiation of stream with timeout?

**Comment by wbogocki** [comment]
I can't paste the code directly but it's basically:

```rust
let stream = TcpStream::connect("ws://place")?;
stream.set_read_timeout(Some(Duration::from_secs(60)));
let client, http_response = tungstenite::client("ws://place", stream)?;
```

Does this help?

**Comment by WestXu** [comment]
> I can't paste the code directly but it's basically:
> 
> ```rust
> let stream = TcpStream::connect("ws://place")?;
> stream.set_read_timeout(Some(Duration::from_secs(60)));
> let client, http_response = tungstenite::client("ws://place", stream)?;
> ```
> 
> Does this help?

Thanks but somehow I can't get it to work.

Firstly, `TcpStream::connect` doesn't seem to accept an url but only a `place:port`. So I end up with this:
```rust
let stream = TcpStream::connect("api.whatever.com:443").expect("Can't connect TcpStream");
stream
    .set_read_timeout(Some(Duration::from_secs(60)))
    .expect("Can't set timeout");
let (mut socket, _) = client(Url::parse("wss://api.whatever.com/ws").unwrap(), stream).expect("Can't init socket");
```
which panics with 
`Can't init socket: HandshakeError::Failure(Http(Response { status: 400, version: HTTP/1.1, headers: {"server": "cloudflare", "date": "Sun, 08 Aug 2021 05:16:42 GMT", "content-type": "text/html", "content-length": "253", "connection": "close", "cf-ray": "-"}, body: None }))`

**Comment by wbogocki** [comment]
That's because in your case the stream is encrypted with SSL. You can use this: https://docs.rs/native-tls/0.2.7/native_tls Btw, I think we're dealing with the same 3rd party service and the same bug on their side. Best of luck :)

**Comment by WestXu** [comment]
Ha I finally got it worked out like this:
```rust
fn connect() -> Result<tungstenite::WebSocket<native_tls::TlsStream<std::net::TcpStream>>, Box<dyn Error>> {
    let stream = TcpStream::connect("api.whatever.com:443")?;
    stream.set_read_timeout(Some(Duration::from_secs(60)))?;
    let stream = TlsConnector::new()?.connect("api.whatever.com", stream)?;
    let (mut socket, _) = client(Url::parse("wss://api.whatever.com/ws")?, stream)?;
    Ok(socket)
}
```

Thanks for the heads up. 

> That's because in your case the stream is encrypted with SSL. You can use this: https://docs.rs/native-tls/0.2.7/native_tls Btw, I think we're dealing with the same 3rd party service and the same bug on their side. Best of luck :)

Don't know which part leaks our supremely confidential secrets, but hey, take care of yourself. 

Hail Hydra.

**Comment by wbogocki** [comment]
Hail Hydra 🥳
