### ISSUE TITLE
Mention minimal required Rust version in readme

### ISSUE THREAD

**Issue by bocc** [snapview/tungstenite-rs#228]
As Tungstenite relies on the const generics MVP that came with Rust 1.51, it would be nice to have this requirement mentioned explicitly.

**Comment by application-developer-DA** [comment]
Hm, I'm not sure about that. I mean, we don't rely on the nightly version or something like this, so as long as the latest stable version is used, it should be fine. I haven't seen the minimal required Rust version mentioned in the most READMEs related to similar libraries so far (maybe I'm mistaken, @jxs correct me if I'm wrong), so I personally don't see much of a value to mention it there. In fact mentioning it there would also mean that someone should track the features added to stable and re-check each release that the minimal mentioned version is still valid (which is especially problematic when we have multiple releases, since the README would only show the minimal version for the current `master`). I.e. I don't find it practical to mention it there.

So I would prefer to close this issue as "won't fix" if you don't mind.

**Comment by jxs** [comment]
Hi, yeah some crates do it like [tokio](https://github.com/tokio-rs/tokio#supported-rust-versions), I have also done it for [refinery](https://github.com/rust-db/refinery#compatibility). I think it doesn't hurt to either set it to `1.51` and keep track of it, or to the latest rust version

**Comment by application-developer-DA** [comment]
Recently `cargo` started to support a new [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) field for that, so I think we're close to have this issue handled!
