### ISSUE TITLE
client is not handling connection problems on your side

### ISSUE THREAD

**Issue by alpinemomo** [snapview/tungstenite-rs#233]
Tungstenite is not handling internet connection problems on your side. If server suddenly dropped connection you can handle reconnection by matching Result Err on stream.read_message() or stream.next(), but if connection is dropped on your side (disabling ethernet adapter or cable disconnection etc) it just freezes.

**Comment by application-developer-DA** [comment]
This is not an issue with `tungstnite-rs` but rather a generic issue with TCP sockets. When you disable the ethernet adapter or disconnect the cable as you mentioned, we must get some special "notification" from the OS so that we read from the socket and get the error to be able to return it to the user. What happens in your case is that once you disconnect the cable, the OS does not immediately know that the socket is 'dead' and we're not 'informed' about this. So it does not freeze actually - eventually the `read_message()` or `stream.next()` **will** fail returning the error. But the time it may take to fail will vary depending on different factors and the OS in question.

If it's important for your application to handle fast disconnects, you must implement this logic on the application level (depending on your business logic), i.e. you can set the timeout for reading operation and/or introduce some sort of a ping/pong every 10 seconds and drop the connection when there is no communication. Without those mechanisms handling all sort of network issues would not be possible.
