### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by psmit** [snapview/tungstenite-rs#252]
I'm looking for a way to specify a connection timeout on a client. Unfortunately, I am not finding this option in the documentation. This option is necessary, as otherwise misbehaving servers can block a client forever.

**Comment by application-developer-DA** [comment]
This is indeed not part of the documentation primarily because it's not quite unrelated to the purpose of the crate ;) The timeouts on the sockets are something that the user can configure depending on the needs of the project. Strictly speaking, `tungstenite-rs` does not deal with the networking part at all, the one can use `tungstenite-rs` to work with any `Read + Write` stream which may or may not have timeouts.

You could use [`set_read_timeout()`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_read_timeout) from the [`TcpStream`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#) and then pass this socket to the `tungstenite-rs`, so that you can get the behavior that you want to implement.

However, we strongly encourage to take a look at `tokio-tungstenite` for real production use-cases since configuring timeouts manually on the `TcpStream` level and making sure that those do not cause resource starvation is a non-trivial task that will require the usage of `mio` and the implementation of the reactor/scheduler to manage the IO and polling the sockets. An efficient implementation is not trivial, thus `tokio-tungstenite` is something that we normally suggest for such cases.
