### ISSUE TITLE
Allow the user to overwrite the `Host` header supplied in the `Request`

### ISSUE THREAD

**Issue by nekolab** [snapview/tungstenite-rs#255]
Hi all 

I know this had been discussed in #227  but I'd really want to re-discuss about the decision.

Currently I'm writing a gateway to do reverse proxying on websocket channel, something like Nginx.
As you may know, in this scenario, the common pattern will look like this:
```

 ┌─────────────────┐  ┌──────────────┐
 │     Gateway     │  │     WWW      │
 │     foo.com     │  │127.0.0.1:1010│
 │    0.0.0.0:80   │  └──────────────┘
 │ /               │
 │ 127.0.0.1:1010  │  ┌──────────────┐
 │                 │  │  API Server  │
 │ /api            │  │127.0.0.1:1020│
 │ 127.0.0.1:1020  │  └──────────────┘
 │                 │
 │ /websocket      │  ┌──────────────┐
 │ 127.0.0.1:1030  │  │  Messaging   │
 │                 │  │127.0.0.1:1030│
 └─────────────────┘  └──────────────┘

```
The gateway will act as a relay, forward the http request and websocket message to the real server.

Here comes the question:
The real uri used to connect is `ws://127.0.0.1:1030/websocket` but the service wants to make sure the
request is from `foo.com` only, so it need to check the `Host` is `foo.com`. Since we forbid modify `host`
header by passing request object, there's no way to make a correct request.

I've read #227 carefully, but a bit confused.

First, let's take a look on RFC
```
12.  Using the WebSocket Protocol from Other Specifications

   The /host/, /port/, /resource name/, and /secure/ flag are usually
   obtained from a URI using the steps to parse a WebSocket URI's
   components.  These steps fail if the URI does not specify a
   WebSocket.
```
It says `/host/ are usually obtained from a URI`, but in some unusual case (like mine), the `host` need
and should could be specified by the caller, this behavior is not violate the RFC

Further more, in my opinion, the RFC describes what the correct protocol should be, but not limiting the
implementation's expand power based on correct behavior by default. Some client (which face to public
end user and have high specialized abilities, like a browser) may limiting the ability due to security concern
and product design but I don't think tungstenite-rs is one of them. 

In general, a library or a tool face to developer seems should provide a correct default value, and allow
end user modify it, at their own risk. it's not a de facto standard violates the RFC, but only provides more
ability. Please think about the http library, we can use it constructs dozens of request violates the RFC but
no one will treat it as "some old/weird library doesn't respect the RFC".

So I'm here to propose releasing the restriction. Actually, I advocate not only the `Host`, all other headers
should be overridable, and the user should take their own risk.

Please kindly leave your comment. If we can reach an agreement, I would happy to create a pull request to make the change.

Thanks

**Comment by application-developer-DA** [comment]
> The real uri used to connect is ws://127.0.0.1:1030/websocket but the service wants to make sure the
request is from foo.com only, so it need to check the Host is foo.com. Since we forbid modify host
header by passing request object, there's no way to make a correct request.

I'm not sure that I understood the problem. When connection is established from the user side, the URI would be `http://foo.com/api` or `ws://foo.com/websocket`, so in both cases the name of the host is properly set. When the connection is relayed to the internal services, the URL will either remain the same with a different port or a different path.

As for overall change, our stance is as follows: we prefer to stick to the RFC / reference specification as much as possible. The reasoning behind this is that violating the RFC **by altering** the specified behavior allows users to bypass certain RFC clauses or even violate them that in turn (on a global scale) contributes to the creation of the faulty applications and spreading the idea of the bad practices being ok just because "many people do it" ("well known product X does it") that entails the normalization of deviance. In a long run it leads to really bad situations in which a [new] implementer of the protocol/technology is not only obligated to read and implement the RFC but also to account for the set of [not clearly documented] problems/violations that have became common in the industry due to someone's else poor decision in the past (which **may** and **often time is** tricky given that such things are not well specified in one place). Such things happened with many different techs and products and have always been a pain to follow and implement. Since we're a relatively popular library in the Rust community for the WebSockets, we try to adhere to those values to not become one of those libraries/frameworks that "promote" the improper behavior.

However, I must say that allowing the change of the aforementioned headers _is probably indeed not against to the RFC_ (strictly speaking) because of the RFC saying "/host/ are **usually** obtained from a URI". "Usually" does not necessary mean "always" or "exclusively", it means "in most cases", so from this point of view I agree with you and think that we can allow changing the `host` (and a couple more other values) by the user.

> Actually, I advocate not only the Host, all other headers
should be overridable, and the user should take their own risk.

I however am not convinced of "**all other headers**" as overriding things like `Sec-WebSocket-Key` and similar parts that are part of the RFC does not seem to be a good idea.

**Comment by nekolab** [comment]
Hi @application-developer-DA 

> I'm not sure that I understood the problem. When connection is established from the user side, the URI would be http://foo.com/api or ws://foo.com/websocket, so in both cases the name of the host is properly set. When the connection is relayed to the internal services, the URL will either remain the same with a different port or a different path.

Let me clarify, user connects to `foo.com` because they connect to the `Gateway`, but the gateway need to connect to the internal service (to make the reverse proxying). You cannot use `foo.com` to connect from gateway to internal service, because the DNS resolution of `foo.com` still points to the gateway, not anyone of the internal service. Also, we want the internal service not aware there's a gateway existing between user and them.

How can we achieve this?
We can either make it by choosing complex mode, create a TCP connection from gateway to 127.0.0.1:1030, bind the stream using `client(req, stream)` method, send the request on stream, and do the rest job.
Or, we can simply build a request, keep everything but modify the authority part of the uri to "ws://127.0.0.1:1030" to tell client to connect to internal server by using `connect(req)`.

I choose the second way and then I realized I cannot do that because there's a `Host` exist in request header and tungstenite refused to use the `Host` I provided, brings me here to create this issue.

> However, I must say that allowing the change of the aforementioned headers is probably indeed not against to the RFC (strictly speaking) because of the RFC saying "/host/ are usually obtained from a URI". "Usually" does not necessary mean "always" or "exclusively", it means "in most cases", so from this point of view I agree with you and think that we can allow changing the host (and a couple more other values) by the user.

I'm happy to know you agree with me that we can modify `Host` header, but still want to discuss more about the RFC.
I have the same feeling with you since we all suffered from the bad consequences. But I still think as a tool providing these function is not related with "violating the RFC".
BTW, may I know your position to the rust `http` library? Like I said in first post, it can constructs dozens of requests violates the http RFC, but I don't think it's a "well known library but do the shaming stuff to destroy the beautiful RFC compatible world".
My opinion is if we want to make world RFC compatible, we need to provide the correct default, educate programmer write RFC compatible **final** product, but not limiting the power of the **tool**.

> I however am not convinced of "all other headers" as overriding things like Sec-WebSocket-Key and similar parts that are part of the RFC does not seem to be a good idea.

Again, I don't think restrict changing it is something maintain RFC compatible. Even in RFC, there's no sentence says "a client must provide the Sec-WebSocket-Key internally and should not let user to choose it". Say what if a user think the default random generator is not good enough and wants to use their own random number implementation?

Tungstenite is a low-level library, can be used in many scenario, maybe it can have it's own product consideration, be a powerful tool, not like a JavaScript `WebSocket` object in browser, do only one thing and hides everything from the programmer. 

Thanks for reading and I'm happy to discuss with you : )

**Comment by nekolab** [comment]
Hi @application-developer-DA 

> and it seems to work quite fine. Or maybe I'm missing something from your use case.

It's a bit complicate, the messaging server need verify the `host` and `cookie` header so I need forward all things I received to the internal server. Since we cannot modify `host` header generated by `tungstenite-rs` internally, I cannot make it work.


And for the http part, it's easy to use `http` crate to create a request violates the RFC, like in https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.7
>    A client that generates an OPTIONS request containing a payload body MUST send a valid Content-Type header field describing the representation media type.

But we can construct the OPTIONS request with body but doesn't contains ` Content-Type` by using `http` library easily

The things I want to express in this example is: since `tungstenite-rs` and `http` are same kind of library, maybe we don't need so much restrictions.

I fully understand since this issue is related with some cognition and philosophy in software development, maybe we cannot reach a final agreement, but it's still helps me a lot and maybe the people reach this issue in future. And it's happy to discuss with you.

At last, as we reached agreement above, I will create a pull request to enable the modification to the default `host` header when I'm ready :)

**Comment by application-developer-DA** [comment]
> It's a bit complicate, the messaging server need verify the host and cookie header so I need forward all things I received to the internal server. Since we cannot modify host header generated by tungstenite-rs internally, I cannot make it work.

Hm, but you can construct any `Request` or just use a string that contains the host and pass it to `tungstenite-rs`. I don't quite get it what what you mean by not being able to modify the host. `tungstenite-rs` extacts the host based on the authority. But since it's the user who passes the `Request` (or anything that is convertable to the `Request`) to the `tungstenite-rs`, you can pretty much construct any request and pass it there. E.g. this would work:

```rust
let request = "ws://127.0.0.1:1030".into_client_request()?;
```

**Comment by nekolab** [comment]
Hi @application-developer-DA 
Yep, but the internal server will validate the `host` is `foo.com` but not `127.0.0.1:1030`
Since we use "ws://127.0.0.1:1030" as an connection string, the `host` will be `127.0.0.1:1030`, set by `tungstenite-rs` and cannot be modified
