### ISSUE TITLE
Invalid header name error in 0.17+

### ISSUE THREAD

**Issue by Alexhol** [snapview/tungstenite-rs#264]
Im using this code to connect
```
use tungstenite::{connect, Message, handshake::client::Request};
use env_logger;
use http;

fn main() {
    env_logger::init();
    let ws_request = Request::builder()
        .method("GET")
        .uri("ws_endpoint")
        .header(http::header::AUTHORIZATION, "header_value")
        .body(())
        .unwrap();
    dbg!(&ws_request);

    let (mut socket, _response) =
       connect(ws_request).expect("Can't connect");
}
```
This code works fine ith  tungstenite = "0.16.0", but with 0.17.0 or 0.17.1 i got the error:
```
thread 'main' panicked at 'invalid header name', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.2.6/src/header/name.rs:1789:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
request output from dbg:
```
Request {
    method: GET,
    uri: ws_endpoint,
    version: HTTP/1.1,
    headers: {
        "authorization": "header_value",
    },
    body: (),
}
```

**Comment by application-developer-DA** [comment]
I think it happens [because of the change](https://github.com/snapview/tungstenite-rs/blob/master/CHANGELOG.md#0170) that we introduced in the latest version, namely: starting from version `0.17.0` if we receive a `Request` as an input parameter from the client, we assume that there was a reason to construct the request the way the client did it (e.g. an "expert mode"), so we only check if it contains the required headers to establish a WebSocket connection and just "pass it through" further. Previous behavior was that we altered the request by appending all required headers, altering the path, deriving the `Host` based on the URI, etc, however, this behavior has been reported as being confusing by a couple of users who constructed their requests in advance and was surprised by the behavior of `tungstenite` overwriting the values of the headers. So the users can choose if they want the `Request` being generated by `tungstenite` or generate it themselves (or the combination of both [see below]). We found this to be the most flexible and sound solution.

This means that in your case, when you actually do not want to construct the whole request yourself (based on what I understood) but instead want to use the "standard logic" extending it by an additional single header, then I would suggest to do it like this:

```rust
let mut request = "was://myhost.com/ws_endpoint".into_client_request()?;
// [..] alter the required header here
connect(request)?;
```

By doing so you let `tungstenite` generate the whole request for you with the possibility to alter specific values (in your case adding an additional header) afterward.

**Comment by matt-walker0** [comment]
@application-developer-DA 
Hi, apologies if this is stating the obvious, as I've just recently started learning rust.
I'd like to add header for authorization without adding manually specifying the rest, I think that is what you mention above (even giving a snippet!). Not sure however how to add to 
`let mut request = "was://myhost.com/ws_endpoint".into_client_request()?;` 
there doesn't seem to be any methods attached to request in this instance?

I was thinking along the lines of request.add_header(key,value);

If its any use, the following worked in Python (push sine wave to Grafana):
`websockets.connect("ws://localhost:3000/api/live/push/sinewave_test", extra_headers={'Authorization': 'Bearer SomeAPIKeyString='}) as websocket:`

**Comment by matt-walker0** [comment]
Think I've figured it out, I'll leave the question up in-case other new people end up in same place.
Solution _(which connects, but maybe could be better?)_

`    let mut request = "ws://localhost:3000/api/live/push/sinewave_test".into_client_request()?;
    request.headers_mut().append(http::header::AUTHORIZATION, "Bearer myAPIKey=".parse().unwrap());`
