### ISSUE TITLE
there is no argument named `header`

### ISSUE THREAD

**Issue by macrodemon** [snapview/tungstenite-rs#265]
I created an empty project with just tungstenite 0.17.1 added to the project I get the following build error:

```
error: there is no argument named `header`
--> \tungstenite-0.17.1\src\handshake\client.rs:134:22
    write!(req, "{header}: {value}\r\n", value = value.to_str()?).unwrap();
                  ^^^^^^
```

removing line 134 fixes the problem

**Comment by application-developer-DA** [comment]
You're probably using the old compiler. Those captures were introduced in Rust 1.58, though you must get a different error since we specified [the minimal Rust version in our `Cargo.toml`](https://github.com/snapview/tungstenite-rs/blob/master/Cargo.toml#L14).

Please consider updating the version of the compiler that you use. Alternatively, you could use the older version of `tungstenite` (0.16) which did not use this feature of the language.
