### ISSUE TITLE
Is there a way to introduce a rate limiter ?

### ISSUE THREAD

**Issue by renozzz** [snapview/tungstenite-rs#284]
The issue is that ping/pong messages are queued/sent automatically and cannot be limited.

**Comment by application-developer-DA** [comment]
Would you please clarify what you mean by limiting them? Answering ping messages with pongs is part of the RFC, we can't simply ignore this part (it would mean that we don't fulfill the requirements of the RFC and that the client/server part of the application that uses `tungstenite-rs` is not quite correct).

Currently, there is no way to turn off automatic pong replies.

**Comment by renozzz** [comment]
For instance, crypto exchanges have limits on the number of messages sent to their servers per second. That includes text and control messages. Reaching those limits would result in a disconnection and even a temporary ban.

A handler for ping/pong/close messages would solve the problem. If any of those handlers are not set, then default ones could be used to satisfy the requirements.

**Comment by application-developer-DA** [comment]
Ok, but if the server sends you a ping message, it should expect a pong back. If the servers in question are not sending any ping messages, no pongs will be sent back. [This behavior we can't ignore](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2). However, we don't send any automatic pings.

In other words: I'm not sure the problem exists. If the server in question sends pings all the time, it must expect pongs in response. If those are not desired, there's no reason to send a ping at the first place 😉

**Comment by renozzz** [comment]
Yes, the server does expect a pong, but in the case of the crypto exchanges the server would wait for a period of time before deeming the connection to be dead. For example, Binance sends a ping every 5 minutes and expects a pong in a 15 minute time frame.

**Comment by renozzz** [comment]
Actually, it has nothing to do with the time but the number of messages. Every message should be sent right away unless the limit is reached. In that case it would block until the limiter "refills" by the "leaky bucket" algorithm for example. 

Yes, optional control of all outgoing messages, including close, would be great. Also, it is critical because at any given moment a pong or a close could be sent back to the server and if the limit is reached that would result in a disconnection and an ip ban if the limit violations persist.

**Comment by application-developer-DA** [comment]
> Yes, optional control of all outgoing messages, including close, would be great. Also, it is critical because at any given moment a pong or a close could be sent back to the server and if the limit happens to be reached that would result in a disconnection and an ip ban if the limit violations persist.

So basically you need a possibility to "block" the standard functionality of the library and instead manage the flow of the messages completely. We currently don't support that (though we thought about introducing a `tungstenite-core` which would only contain logic for parsing and composing messages without the rest of the logic), though it's questionable if WebSockets is the right choice for such a use-case.

You currently can't turn off the behavior of replying to pings and replying to close messages, however since the `tungstenite` is stream-agnostic, you can actually use a custom stream to read from/to. I.e. you can implement your own wrapper for `tungstenite` (or `tokio-tungstenite`) and implement any logic you wish on top of it 😉

**Comment by agalakhov** [comment]
> What happens when someone decides to spam it with pings ?
What happens when someone decides to spam it with something else, i.e. TCP SYN or legitimate messages?

We wrote the library in such a way that it is possible to add any functionality by just replacing some parts. It is possible to use rate-limited stream in place of `TcpStream`, you may use a non-blocking stream and decide _when_ to call `read`. You can also detect and drop connections that are abusing pings. If this is still not enough, we provide frame-level API as well, so that you can implement your own WebSocket handling just using our building blocks.

**Comment by renozzz** [comment]
Great. Just the initial replies were rather uninspiring. 

Also, this relates to #283

**Comment by Akuli** [comment]
> You can also detect and drop connections that are abusing pings.

So I would handle `Message::Ping` when receiving, and close the connection if I previously got another ping less than a second ago (or similar). In either case I shouldn't send `Pong`, because that happens automatically.

Is my understanding correct?

**Comment by application-developer-DA** [comment]
> So I would handle Message::Ping when receiving, and close the connection if I previously got another ping less than a second ago (or similar). In either case I shouldn't send Pong, because that happens automatically.
> Is my understanding correct?

It's up to you. We automatically reply to ping messages with pong (as per RFC), however you can always send a pong message if you want to.
