### ISSUE TITLE
WebSocketConfig docs

### ISSUE THREAD

**Issue by Akuli** [snapview/tungstenite-rs#285]
After reading the docs, I am still confused:
- `max_send_queue`: How does this work with `tokio-tungstenite`? Specifically, I want sending to always block (basically no send queue), so that a malicious user can't fill my server's memory by never receiving their frames, and instead I rely on TCP to take care of flow control. I tried setting `max_send_queue` to 0 and immediately got a `SendQueueFull` error. Then I tried setting it to 1, and seems like I don't get `SendQueueFull` anymore, but I'm not sure if I can rely on it.
- `max_message_size` and `max_frame_size`: I was wondering whether these apply to sent frames. Turns out they only apply to received frames, but I had to read the source code to find out. This matters to me, because my application sends relatively large frames, sometimes a couple kilobytes, but only needs to receive max 3 bytes at a time in a frame.

**Comment by application-developer-DA** [comment]
- `max_send_queue` works as documented for `tungstenite-rs`, however the specifics of the `send()` function that comes from the trait used in `tokio-tungstenite` has a behavior that might be not particularly clear. There are some implications of the way how we implemented the `Sink` for the `WebSocketStream` in `tokio-tungstenite` that plays a role in the buffering of the messages. You can check this discussion where I tried to document the behavior. Perhaps we need to document the behavior in `tokio-tungstenite` somewhere (as it's only specific to Tokio).
- `max_message_size`, `max_frame_size`: they should work as documented, so you can cap the reception of messages using them. You can of course also limit the size of the outgoing messages since you have complete control over the data that you write to the stream, e.g. you can check the size of the data before sending and drop or fragment it before sending if required, so we don't limit the sending of data **, in addition,** to what the user code might be doing.

Hope this answers your questions. Regarding `max_send_queue` we probably definitely need to mention this thing in the `tokio-tungstenite`, you're the second person asking this, so it might be useful to document such intricacies.
