### ISSUE TITLE
Connection.read_message() alternative that does not allocate

### ISSUE THREAD

**Issue by smabie** [snapview/tungstenite-rs#297]
Hi, 

I'm using tungstenite right now in an ultra low latency/high performance capacity and was wondering if there's any plans for writing a zero allocation version of `read_message()` that simply re-uses an existing buffer/slice/vec?

Thanks!

**Comment by application-developer-DA** [comment]
Hey, that would be a nice addition indeed. We had an idea to move the WebSocket-related logic into its own small crate (something like `tungstenite-core`) so that we could reuse it in `tungstenite-rs` (allowing others to use `tungstenite-core` directly in case they don't want the buffer management).

This question has actually been asked a couple of times in the past, you may want to look at the current open issue about that: https://github.com/snapview/tungstenite-rs/issues/209 (I think it's about the same thing)

And one that is closed: https://github.com/snapview/tungstenite-rs/issues/172

I'll close this issue since it looks like a duplicate for:

- https://github.com/snapview/tungstenite-rs/issues/209
- https://github.com/snapview/tungstenite-rs/issues/22

Unfortunately, we have not yet worked on that (was not particularly useful for our specific case), but it's definitely a doable thing to achieve (would require some refactorings to make the underlying frame parsing logic not store any buffer inside, but relying on the buffer provided by the user).
