### ISSUE TITLE
Consider using mio or something similar

### ISSUE THREAD

**Issue by nox** [snapview/tungstenite-rs#3]
In the current code, there is one thread per websocket connection, right? Are there plans to use mio or something similar to be able to have many client connections on a single thread? Feel free to close this if it's completely nonsensical.

**Comment by application-developer-DA** [comment]
`tungstenite-rs` is a light-weight library which allows you to use websocket on top of the stream you provide to the `tungstenite::client::connect()` (client side) or `tungstenite::server::accept()`. So basically it will work with any stream which supports `Read + Write`.

It may not be obvious at the first sight, because we have not published the link to the documentation and probably did not stress it enough inside the README. I think we will update the documentation soon and so you will get what I mean.

You can add mio support easily on top of it. All what you need is to construct the `TcpStream` from mio and pass it to one of the mentioned functions. In case if you need futures/tokio support, we already provide those bindings (built on top of the `tungstenite`) in a separate repository: [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite).

Jason Housley (the author of ws-rs) also mentioned that in his latest comment: https://github.com/housleyjk/ws-rs/issues/74#issuecomment-287934043

So the short answer is that we do already support both `mio` and `tokio`.

> In the current code, there is one thread per websocket connection, right?

No, `connect()` is just a helper function which uses the blocking sockets by default. Probably we will move it inside the helpers module or even in a different repository.

> Are there plans to use mio or something similar to be able to have many client connections on a single thread?

`mio` version can easily built on top of `tungstenite`, see the comment above. As for other things like `futures` and `tokio`, they are already supported in `tokio-tungstenite` which resides in the repository next to the `tungstenite`.

**Comment by application-developer-DA** [comment]
If you're familiar with `tokio` and `futures`, here are some examples of how you can use it with tokio: https://github.com/snapview/tokio-tungstenite/tree/master/examples

The `server.rs` implements a simple a WebSocket chat server, the server uses only 1 thread for all connections, it performs even faster than `ws-rs` by the way.

**Comment by agalakhov** [comment]
Tungstenite is made similar to SslStream: it has nothing to do with threads at all. You provide the underlying stream, Tungstenite wraps it into a WebSocket. If your stream is non-blocking, Tungstenite will be non-blocking as well, just like SslStream is. You may run it on top of about everything: std::net::TcpStream, mio::tcp::TcpStream, openssl::ssl::SslStream etc. If your stream blocks, Tungstenite will block. If your stream returns WouldBlock, Tungstenite will return it as well in a clean way.

We use Tungstenite in two closed-source projects, client and server. The client runs tokio-tungstenite, while the server runs mio.

**Comment by nox** [comment]
Thanks to both of you!
