### ISSUE TITLE
Help handling very large messages

### ISSUE THREAD

**Issue by WyseNynja** [snapview/tungstenite-rs#304]
Hello! Apologies if the issue tracker isn't the right place to ask this. Happy to be pointed somewhere better if that is the case. I've been using tungstenite through tokio-tungstenite for several projects and its always been a breeze. But my current project has run into an issue.

I am building a websocket proxy that speaks JSONRPC. My users send a request to the proxy, the proxy relays the requests to one of a bunch of servers and then forwards the response back to the user. It keeps a mapping of the "id" fields of each request and response so they can be sent to the right place.

Now the problem: What I have works, but it has to read the entire request/response before it can proceed. The largest response I've found is huge at 71GB. Those 71GB have to copy into my program's memory before I can swap the ids and before I can begin forwarding the response back to the client.

Possible solution: I'm hoping that there is some way to read the response until the id is found, modify the id from my mapping, and then stream the entire message with the corrected id back to the client as the rest of the 70+ GBs arrive. This will both make the proxy more responsive and keep my program's memory lower.

Is this possible with tungstenite? Am I thinking about this the wrong way? Any suggestions? I've read some of the other issues here and it looks like the message has to own the data (https://github.com/snapview/tungstenite-rs/issues/209) which makes me think this isn't possible with tungstenite, but I wanted to be sure before I dug in too deeply.

**Comment by application-developer-DA** [comment]
Hey,

I think it's possible to implement the intended logic, though with some caveats.

First of all, let me share one of the recent issues that also dealt with the handling of the large message: https://github.com/snapview/tungstenite-rs/issues/303 It was a similar yet different topic of sending a message before it's fully accumulated on a sender side, but I think it might be useful to get some insights about the w

For your particular case the problem seem to be on a receiver side where you want to see the beginning of the large message before proceeding with the rest. In WebSockets, the highest abstraction that is easy to reason about is a message. That's what `tungstenite` exposes to the user to work with. A single message can consist of one or multiple frames. In your case it seems like you want to read **frames before they get fully received** , i.e. as if it was a regular TCP connection without any additional protocol on top of it. While this would be **theoretically** possible (WebSockets is just an abstraction on top of a regular TCP), this would question the need for the WebSockets as such since peaking the not-yet-completed frames is like reading from the TCP stream directly. So we don't really provide such a low-level API to the user (it would have many implications like users being responsible for sticking to the RFC in order to implement the proper handling of different WebSockets concepts etc).

In your particular case, _unless you want to opt-in for a regular TCP connection_ (which probably would suit better for your task), I would suggest to split the response into multiple WebSocket messages. This would allow you to get the header part (that would contain the routing information like the `id` that you mentioned) followed by the "body" of the response via separate messages.

However, if you're sending 71 GB of data over WebSockets a couple of WebSocket messages, it might be not the best tool for this particular job :)

Hope this helps!
