### ISSUE TITLE
socket closes without error on hibernate / standby

### ISSUE THREAD

**Issue by Proxtx** [snapview/tungstenite-rs#306]
When putting a (windows-)PC into standby (/hibernate) the loop (when using this syntax: ```loop { read_message() } ```)pauses never to start again. Also no error is thrown so I can't reconnect. This has happend to me accross multiple projects.

**Comment by agalakhov** [comment]
How do you detect that the socket is closed?

In general, you can't rely on certain network behavior on standby. It is better to detect standby itself.

**Comment by Proxtx** [comment]
The server reports that the client disconnected (maybe unexpectedly idk).

I would like to implement something that detects a standby but how do I do that while being stuck in the loop. The program is stuck in the loop because it's still waiting for the read_message call. 

I handle a closing by trying to reconnect to the server every 5 seconds but that fallback is not triggered after a standby.

**Comment by agalakhov** [comment]
The server closed the socket, the client didn't even notice. The socket remains open at the client side.

Just send ping periodically. Or, better. send some useful information, not just pings. If there is any activity on the connection, the disappearing of the server won't remain unnoticed.

**Comment by Proxtx** [comment]
Ok thanks...
But how do I send data periodically since I'm stuck in the loop.

**Comment by agalakhov** [comment]
Then just don't make such loops. It is generally a bad idea since your application is irresponsible for the time of waiting. The software architecture is up to you.

**Comment by Archieeeeee** [comment]
I have same problem here, detecting  state change is easier on the web which has `onClose` event api, see `https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close_event`

**Comment by daniel-abramov** [comment]
I have to close this issue since it has nothing to do with this library, the described behavior is the behavior of the TCP sockets.

`read_message()` "hangs" in such scenarios (in a blocking mode) when there is no data to read and no indication on the socket that the socket is closed. Should the fast detection of such stalled connections be necessary, you must ensure that you handle it by e.g. not blocking on reading indefinitely or by setting keep alive options on the socket or OS level, there are many solutions to the problem that range from settings keepalive timeout + interval + retries + RTO timeout to running pings or some sort of a heartbeat at regular intervals and assuming the socket dead if these are not acknowledged or no regular messages are received.

The simplest way would be taking `tokio-tungstenite` and combining reads with a timeout (or with a task that sends regular pings or expects pongs/ping to arrive from the other side).

There is nothing we can (or should) do on a crate level as we can't just bluntly introduce some behavior of monitoring the state of the NIC or some "hidden" pings/pons.
