### ISSUE TITLE
Reconnection

### ISSUE THREAD

**Issue by wisespace-io** [snapview/tungstenite-rs#32]
How to re-establish the connection back the server? Would be possible to provide an example?

**Comment by application-developer-DA** [comment]
Well, we could add an example, but basically to re-establish the connection, you have to simply connect with websocket again (like you did when you initially set up the connection). Reconnection here is simply establishing a new connection, because if the connection is gone, then the only way to "reconnect", is to simply connect again.

**Comment by wisespace-io** [comment]
@application-developer-DA I think you are right. The solution is quite simple, it seems to work fine in my project, Just wait 5 seconds after disconnected to automatically try a new connection.

https://github.com/wisespace-io/nettfiske/blob/master/src/main.rs#L98
