### ISSUE TITLE
Problem with reading messages

### ISSUE THREAD

**Issue by ErikbStorm** [snapview/tungstenite-rs#331]
Hi,

I have a problem with the read_message function. My code works for a couple of hours and then gets stuck on reading the messages. The message gets matched, so close frames should be caught and the loop should end. So I do not know why this happens. 

Any help on why this happens would be very appreciated.

![image](https://user-images.githubusercontent.com/36201012/212278135-f356c3d1-13a7-418b-b151-4e51ddfe3339.png)
As can be seen in the image. The program did not finish and it is stuck reading the message.

**Comment by daniel-abramov** [comment]
It's hard to tell what's going on based on a screenshot since it does not provide a reproducible code, but the most likely scenario is that you just don't get any data from the other side. You may introduce an additional timeout and close the stalled connections in such cases (it could be either the other side hanging or the other side not sending anything). If the connection hangs on the other side, the OS may only spot it after quite a long time (eventually it would return an error though).

**Comment by ErikbStorm** [comment]
Thank you for the answer. Does tungstenite implement a timeout on idle connections? I am rewriting some python code in Rust and I used this library: `https://websockets.readthedocs.io/en/stable/faq/common.html#how-do-i-keep-idle-connections-open` which sends a ping every 20 seconds and if it does not respond then it closes the connection. Is something like this also implemented in tungstenite or not?

**Comment by daniel-abramov** [comment]
We do not introduce any implicit timeouts inside the library since that would be a behaviour that no one expects (we have an extensive user base, all of which have different tolerances based on the service they're writing), so making this decision for the user would be incorrect. However, we support all WebSocket messages, including pings and pongs, so writing the timeout logic in a user application can be as simple as 10 lines of code (feel free to browse through the issues, we've included some examples here and there).

I.e. you can create a timer and send pings (or mandate unidirectional pongs) every N seconds and consider the connection dead if no pong is received within N seconds.

I would recommend using `tokio-tungstenite` for any practical purpose though (implementing such timeout logic with Tokio is quite a trivial thing).
