### ISSUE TITLE
Is it possible not to enforce frame max size limit

### ISSUE THREAD

**Issue by HollowMan6** [snapview/tungstenite-rs#340]
Hi! I'm relying on [rust-headless-chrome](https://github.com/rust-headless-chrome/rust-headless-chrome/issues/385) to generate some pdf files from web pages. I'm noticing that, if I try to generate some pdf files that is relatively large, like 25MB, the pdf generation will fail with error `Capacity(MessageTooLong { size: 47175864, max_size: 16777216 })`, which eventually leads me here, as rust-headless-chrome has the tungstenite v0.18.0 dependency. https://github.com/rust-headless-chrome/rust-headless-chrome/issues/385

Then I tried to disable the frame max size limit and see if there would be any error or panic for the same pdf generation process. https://github.com/HollowMan6/mdbook-pdf-tungstenite/commit/632185567b4b9118ada457509e966585b8d19b2e Then to my suprise, the pdf generation actually works well, so now I'm wondering why you have this limit check. If it's about the security or specification reasons, would you add some kind of option to allow us to bypass this check so that the rust-headless-chrome can support large pdf files generation? Thank you!

**Comment by daniel-abramov** [comment]
Hey! We do actually allow users to specify the maximum size of the frame. I.e. you don't really need to modify `tungstenite` to allow the behavior, you simply can pass the reasonable value (or max value) [to the client config](https://docs.rs/tungstenite/latest/tungstenite/protocol/struct.WebSocketConfig.html) when creating a WebSocket connection.

So perhaps instead of using [`connect()` helper](https://github.com/rust-headless-chrome/rust-headless-chrome/blob/200e3761d561f4fd3ef3da9cd57f8c1cdcb1d032/src/browser/transport/web_socket_connection.rs#L134) (that's what rust-headless-chrome uses), you could use [`client_tls_with_config()`](https://docs.rs/tungstenite/latest/tungstenite/fn.client_tls_with_config.html).

**Comment by sampaioletti** [comment]
Sorry to ask in an old issue, but why doesn't the library split messages smaller than the max frame size, but smaller than the max message size into multiple frames? Seems like the wrong error, the issue in the above scenario would be a ```FrameToLong``` not ```MessageToLong``` 

Is it intended to manually split into frames if the max_frame_size < payload < max_message_size? I implemented a message codec in our application for the rare case a large message needs transmitted, but reading this again it feels like it could have been handled with framing.
