### ISSUE TITLE
benchmark result to compare with other crates

### ISSUE THREAD

**Issue by davemilter** [snapview/tungstenite-rs#352]
In [reddit discussion](https://www.reddit.com/r/rust/comments/1367sax/fastwebsockets_a_new_highperformance_websocket/)  of new websocket crates, mentioned benchmarks results for websockets crates:

```
web-socket:  32.26691ms
fastwebsockets:  38.675652ms
tokio-tungstenite: 142.147423ms
```

code for benchmark [here](https://github.com/nurmohammed840/web-socket-benchmark). It is just send/receive. May be somebody would be interesting to improve not the best results for "tungstenite".

**Comment by daniel-abramov** [comment]
It's true that `fastwebsockets` implementation from Deno folks is faster (kudos to the authors), but not to the extent that has been stated by the author of the benchmark.

I took a quick look at the benchmark and I would not really use it as a fair comparison - the author compared `tokio-tungstenite` and `fastwebsockets` to his own library and seemed to be biased towards his own implementation. After checking his implementation and being aware of the [discussion on Reddit post](https://www.reddit.com/r/rust/comments/123vevv/yet_another_websocket_implementation_in_rust/), it does not feel particularly trustworthy (to be honest, it felt like a mild attempt to pitch own implementation by the author).

The folks from `fastwebsockets` [shared some benchmarks recently](https://github.com/denoland/fastwebsockets/tree/main/benches). I have not seen the code for the benchmarked versions, but it looks closer to what I would expect to see in reality, i.e. `fastwebsockets` is clearly faster, but not 4 times faster!

We know that there are some areas to improve the performance of `tungstenite` even further, but unfortunately, none of the original authors/maintainers uses (or actively works with) WebSockets at the moment, so the development of the performance improvements stalled. Should someone require a better performance, the PRs are welcome!

The required improvements are known to us and we've discussed them in the past:
1. https://github.com/snapview/tungstenite-rs/issues/36
2. https://github.com/snapview/tungstenite-rs/issues/96
3. https://github.com/snapview/tungstenite-rs/issues/209
4. https://github.com/snapview/tungstenite-rs/pull/342

I'm confident that after addressing these points the gap in performance between `tokio-tungstenite` and `fastwebsockets` will be quite negligible.

The essence of the aforementioned problems:
- The API surface. Nowadays, `tokio-tungstenite` (wraps `tungstenite`) is the preferred way to use `tungstenite`, but the `tungstenite`'s API surface does not perfectly align with what we would need for `tokio-tungstenite`: [we need to split certain public functions of `tungstenite` and make their semantics more suitable for the async world](https://github.com/snapview/tungstenite-rs/pull/342) and we demand the streams to be `Read + Write` which is not necessary and [severely overcomplicates](https://github.com/snapview/tokio-tungstenite/blob/master/src/compat.rs) the `tokio-tungstenite`. We also demand that incoming messages own the data that makes us slower on benchmarks since the caller must own the message before passing it to `tungstenite` / `tokio-tungstenite` (so oftentimes you'll see benchmarks doing `send(message.clone())` with `tokio-tungstenite` while other implementations would simply do `send(&message)`). Also, we read using rather small chunks (compared to what `fastbuffer` uses).
- We don't support SIMD and vectored writes at the moment.

Ideally, we would need to refactor it into a sans I/O implementation of WebSockets and use it from `tokio-tungstenite`.

**Comment by reneleonhardt** [comment]
@daniel-abramov Could there be a section added to the README which compares Tungstenite with other popular implementations, what are the advantages?
