### ISSUE TITLE
How to set asymmetric limits on WebSocket message size?

### ISSUE THREAD

**Issue by mkpankov** [snapview/tungstenite-rs#380]
Hello,

I'm forwarding a [discussion](https://github.com/tokio-rs/axum/discussions/2250) started in axum, because it essentially boils down to what tungstenite supports.

> In axum, there's this WS setting:
> https://docs.rs/axum/latest/axum/extract/struct.WebSocketUpgrade.html#method.max_message_size
> 
> In our project, we'd like to limit messages clients are allowed to send over WS to something really small compared to the default - like 40 KB. At the same time, we'd like to set no limit on messages sent by the server (or set a much higher limit, like 2MB).
> 
> This is to, at least, prevent resource exhaustion / DoS attacks where server would read big messages that would consume server memory.
> 
> I understand it's not straightforward, so I'd like to hear some ideas on what to research, is it possible at all, and does it make sense.

**Comment by mkpankov** [comment]
Looks like most of the parts are already there.
It should be possible to look at `self.role` [here](https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/mod.rs#L613) and use a different field in config (say, `max_client_message_size`).
We're willing to contribute a solution in case it will be accepted upstream.

**Comment by daniel-abramov** [comment]
Hey, I'm not quite sure I understand the semantics of such a field. If the only thing that the `max_client_message_size` would do is reject outgoing messages that exceed the configured size, then the whole check is nothing but a single if in the function that accepts a message. I'm not sure this is very useful given that it could be easily achieved by simply wrapping a WebSocket stream into another wrapper that checks the size of the outgoing message prior to forwarding it to `tungstenite`.

**Comment by finnbear** [comment]
Something I've personally wondered, also from a DoS perspective, is if the _current_ single max message size parameter affects only incoming messages or both incoming and outgoing messages.

**Comment by mkpankov** [comment]
@daniel-abramov hey, issue is I'm not interacting with `tungstenite` directly. Issue is from `axum` initially. I'm the application developer so I'm not sure where the solution would fit.
I've posted to the axum [discussion](https://github.com/tokio-rs/axum/discussions/2250#discussioncomment-7401896) thread as well.
I think I suggested it here because looking at the code, implementation is straightforward (just a symmetric field and check). I'm not arguing it's the best implementation possible though.

**Comment by daniel-abramov** [comment]
> I agree that adding a parameter for outgoing message size limit is unnecessary, but it would be useful to limit incoming messages without limiting outgoing messages (if this is not already the behavior).

You're right - that's the current behavior. I've just added a tiny change in the docs so that it's more explicit.

> I've posted to the axum https://github.com/tokio-rs/axum/discussions/2250#discussioncomment-7401896 thread as well.
> I think I suggested it here because looking at the code, implementation is straightforward (just a symmetric field and check). I'm not arguing it's the best implementation possible though.

Ok, so I've checked the discussion and I agree with `axum`'s author, though I don't quite understand why an extension of either `axum` or `tungstenite` would be required (if I'm getting your issue right), i.e. I don't understand why patching of either library is required for your particular use case. If I'm reading it right - in addition to limiting the maximum size of the incoming message (that can be configured in both `axum` and `tungstenite`), you also would like to limit the maximum size of the outgoing messages, i.e. the messages that you're sending over `axum` (that in turn uses `tungstenite`). If that's the case - doing so is just a user-land logic that can be written as a part of an application. Or do I miss anything?

**Comment by mkpankov** [comment]
Closing as expected change is on client side

**Comment by mkpankov** [comment]
@daniel-abramov Hello! I've been trying to come up with a prototype of what you suggested. Code is [here](https://github.com/mkpankov/ws-asymmetric-message-size/blob/main/src/main.rs).
Few comments:
1. It uses axum for HTTP, hope it's not too hard to understand what's going on. It's just easier to setup this way
1. It splits the websocket because that what I need in production
2. `text.push('F');` is to illustrate that server message is bigger than client one so `max_message_size` will break the scenario
3. It "works", meaning it compiles and runs, but it doesn't serve its purpose. By the time `receiver.next().await` returns, message of arbitrary size has been read and constructed in tungstenite's internal buffers, effectively consuming arbitrary amount of memory. I remember about 64MB default limit, it's still too big. My expected number of clients is on scale of 10000. So I want to set "client message size" to about 40kB, while still being able to send arbitrary messages from server.

If I run this, and send `01234567` (using [websocat](https://github.com/vi/websocat), but it doesn't matter), I get the following server output:
```
Hello, world!
Server started
Handling socket
Breaking the loop manually
Exiting
```
Assuming "to be implemented asymmetric limit", the expectation is :
```
Hello, world!
Server started
Handling socket
<some tungstenite error about message size limit>
Exiting
```
i.e. `receiver.next().await` should return an error as soon as message size limit is exceeded.

I hope I didn't misunderstand your intention in what "user-land logic" would look like here. I'm open to either clarifications or suggestions here.

**Comment by daniel-abramov** [comment]
Ok, but I can't quite see where you set [this option though](https://docs.rs/axum/latest/axum/extract/struct.WebSocketUpgrade.html#method.max_message_size). Tungstenite will return an error, but only if you set this option to the desired value. 

To recap:
- you can limit the **incoming** message size in tungstenite
- you can limit the **outgoing** message size in the user code

So, from what I can see in your example code, you did not limit the incoming message size (no option is set), you're only limiting the size of the outgoing message (reply), or, to be more precise, you don't reply to messages that are larger than `8`.

**Comment by mkpankov** [comment]
I've updated the [example](https://github.com/mkpankov/ws-asymmetric-message-size/blob/main/src/main.rs). `max_message_size(8)` results in server not being able to send messages more than 8 bytes. So the problem is client limit is smaller than server.
![image](https://github.com/snapview/tungstenite-rs/assets/393741/e4b267da-0ee0-4155-ab01-6dba1c9ba41d)

**Comment by daniel-abramov** [comment]
I'm not sure I understand "the problem is client limit is smaller than server".

You start a server with a configured maximum size of the **incoming** message set to `8`, hence when the message is received that is larger than `8`, you get an error. So far it works as expected. Your current example limits the size of the incoming messages and does not limit the size of the outgoing messages and behaves exactly as it's written. I'm not sure where you see a problem 🙂

**Comment by mkpankov** [comment]
The error is after `Replying`. It's when sending the reply from server. Because reply is 1 byte longer than the request. `max_message_size` limits both incoming and outgoing messages.

**Comment by daniel-abramov** [comment]
No, this is not quite correct. This is what happens in your case:

1. The server receives the first message and replies to it (all good).
2. The server receives the second message and rejects it immediately (because it's larger than the configured maximum size of the incoming message).

It **does not** fail when trying to send the reply, it fails earlier while reading the incoming message.

**Comment by mkpankov** [comment]
You're right. I guess that solves the issue entirely (scenario is already covered).
Thank you for your time.
