### ISSUE TITLE
Why is EWOULDBLOCK considered an error during the initial HTTP upgrade handshake?

### ISSUE THREAD

**Issue by hbina** [snapview/tungstenite-rs#422]
![image](https://github.com/snapview/tungstenite-rs/assets/6733660/3f32f0e1-00f5-4bfd-a0a4-c6cdf0324159)

Specifically, in this loop to write the HTTP upgrade request to the server why does it specifically check for the EWOULDBLOCK error? See https://github.com/snapview/tungstenite-rs/blob/master/src/handshake/mod.rs#L38-L53

I thought that upon getting EWOULDBLOCK, all you have to do is to just try again? At least that is what I understood from reading a bunch of random articles on the net.

**Comment by agalakhov** [comment]
Because the operation is not done.

In general, there are other errors that require operation repeating. Other examples are long-range lossy transmission (communication error = try again), printing something on paper (no paper = wait until more paper is loaded and try again), reading magnetic tapes, floppies or sometimes CD-ROMs (reading error = try again several times and onlygive up if all attempts fail) and so on.

There is a consensus that, if some operation is not completed for any reason, it is an error, and possible actions are then "abort, retry or ignore", depending upon what exactly happened. By this definition, EWOULDBLOCK is an error that usually requires retry, while for example EOVERFLOW requires abort or sometimes ignore, and ENODEV may require abort or ignore, but sometimes also requires retry if there are chances that the device appears later. So, EWOULDBLOCK is not an exception. It follows the general rule of error handling and is just one of many typical errors that may require retry.

In fact, EWOULDBLOCK even doesn't *always* require a retry. If the function is called immediately after `poll()`/`select()`, it can't return EWOULDBLOCK under normal circumstances, which makes EWOULDBLOCK a fatal error in this case, sinceit indicates a bug then.

**Comment by hbina** [comment]
In that case, what is so special EWOULDBLOCK then? Since the `single_round` function specifically converts EWOULDBLOCK into a non-error via `no_block`, returns `Ok(....)` only to be converted into an error again 1 call stack above?

![image](https://github.com/snapview/tungstenite-rs/assets/6733660/5cae3261-7c5a-4d33-bbc8-6218478dc17e)

Wouldn't something like this be enough?

![image](https://github.com/snapview/tungstenite-rs/assets/6733660/f6835edf-8d91-4e01-b6d1-bb6a8f33d9d4)

Sorry if this is not the right place to ask questions, I am trying to go through the WebSockets RFC and implementations. If you have more proper place to have Q&A i would move this discussion there.

**Comment by agalakhov** [comment]
That's because WebSockets work over TCP.

As said above, there are errors that may require retry. But there are many errors that never require retry (the function is guaranteed to fail again; for example, a "divide by zero" error is not to be retried, since division by zero always fails).

A TCP connection may produce many different error, and most of them are fatal. They render connection unusable and one has to close it and start over from the very beginning, re-establishing connection and so on. EWOULDBLOCK just happened to be *one and only* TCP error condition that isn't fatal. *Theoretically speaking*, there could be other non-fatal errors, but all possible errors are listed in operating system documentation, POSIX and/or Rust standard library documentation, and there is nothing of interest on the list except for EWOULDBLOCK.

In principle, we could rename `no_block()` to `non_fatal_error_is_ok()` with `EWOULDBLOCK` being one and only non-fatal error.

**Comment by hbina** [comment]
> EWOULDBLOCK just happened to be one and only TCP error condition that isn't fatal. 

This is exactly what confuses, judging from the code, it effectively treats EWOULDBLOCK as fatal anyways. Basically I don't see the point of having RoundResult::WouldBlock if all it does is just redirect errors.

If what you said is true -- EWOULDBLOCK is a special error where you can simply retry -- then shouldn't this block,

```rust
pub fn handshake(mut self) -> Result<Role::FinalResult, HandshakeError<Role>> {
        let mut mach = self.machine;
        loop {
            mach = match mach.single_round()? {
                RoundResult::WouldBlock(m) => {
                    return Err(HandshakeError::Interrupted(MidHandshake { machine: m, ..self }))
                }
                RoundResult::Incomplete(m) => m,
                RoundResult::StageFinished(s) => match self.role.stage_finished(s)? {
                    ProcessingResult::Continue(m) => m,
                    ProcessingResult::Done(result) => return Ok(result),
                },
            }
        }
    }
```

looks like this?
    
```rust
/// Restarts the handshake process.
pub fn handshake(mut self) -> Result<Role::FinalResult, HandshakeError<Role>> {
    let mut mach = self.machine;
    loop {
        mach = match mach.single_round()? {
            RoundResult::WouldBlock(m) => m,
            RoundResult::Incomplete(m) => m,
            RoundResult::StageFinished(s) => match self.role.stage_finished(s)? {
                ProcessingResult::Continue(m) => m,
                ProcessingResult::Done(result) => return Ok(result),
            },
        }
    }
}
```

The way it is now, it will fail the initial handshake.

**Comment by agalakhov** [comment]
It isn't fatal, it is returned to the user after doing some preparations. The user decides then if it is fatal or not.

What happens here: after EWOULDBLOCK *our code* can't continue, but *user's code* is likely to do a retry. (In fact, in an asynchronous environment like `tokio-tungstenite` it will *definitely* do a retry, that's how async works.) That means, we have to do a little more than just fail.

Normally we try to send and then to receive. Both send and receive may return EWOULDBLOCK independently of each other. If send blocks, it does not mean that receive would block too, and vice versa. We try to send first. If sending is impossible right now due to too many data waiting in the outgoing buffer (that's what EWOULDBLOCK for send actually means), we just skip sending and continue with receive instead. Receive either returns a packet or says "EWOULDBLOCK", which in this case means "no incoming data yet". Both results are returned to the user. Here, in case of EWOULDBLOCK we carefully keep WebSocket in the usable state, while for other errors we don't care (all other errors mean broken connection and retrying doesn't work anyway).

One more point: a normal `TcpStream` as created in Rust **never** returns EWOULDBLOCK. It just blocks and waits until the blocking condition disappears. But one can reconfigure `TcpStream` to a non-blocking mode, in which it never blocks and returns EWOULDBLOCK instead. The user does this in order to implement their own blocking by other means (usually in order to be able to handle many connections at once or do some computations in background). Take a look at the `select()` system call to get an idea.

Imagine a traffic jam. You can just drive in and stay in the jam, and sooner or later you'll reach your destination. That's the blocking mode, the `TcpStream`'s default. Or you can see a jam and go to a coffeehouse until the jam disappears, and only drive if there is no jam. This is EWOULDBLOCK. It just means "wait for some time, then retry". And, since we do multiple operations at once, we try to make as much progress as possible. That's why we handle it in such a way. Seeing a traffic jam does not prevent us from opening garage door or sitting in the car, we can even start, we just can't reach our destination right now.

Take a look on `tokio-tungstenite` and on `mio`. Both take advantage of EWOULDBLOCK.

**Comment by daniel-abramov** [comment]
This issue seems to be stalled, so I went through the discussion, and my feeling is that the author's confusion is not caused by a misunderstanding of the semantics of `EWOULDBLOCK` but rather by a slightly peculiar part of our handshake API - most of the parts of our library that deal with I/O look like this:

```rust
impl WebSocket {
    fn read_write_or_something_else(&mut self) -> Result<CompletedResult, Error>;
}
```

where EWOULDBLOCK is essentially returned to the user **as is** and the user can decide what to do next (oftentimes repeat it once ready). However, it's only the handshake part of the library that has a different API:

```rust
impl Handshake {
    fn handshake(mut self) -> Result<Completed, HandshakeError>;
}
```

where `HandshakeError` is an enum with two variants: `WouldBlock(handshake)` and `FatalError(error)`, and the corresponding internal handshake parts have a separate error type `WouldBlock(machine)` respectively. This causes confusion regarding a "special handling" of `EWOULDBLOCK`. The only reason why the handshake part looks like this is because the function that performs I/O takes `self` by value (not by [mutable] reference like in other parts of the library), which means that without **wrapping** `EWOULDBLOCK` into a special error type containing the original [consumed] value, there would be no way to repeat the operation. I have a feeling that **this part** is what creates the confusion (based on snippets that the author posted).

And so, to answer the original question, @hbina - yes, _with certain changes in the code_ **it is possible to get rid of a** ["special handling" (type) for `EWOULDBLOCK`](https://docs.rs/tungstenite/latest/tungstenite/handshake/machine/enum.RoundResult.html#variant.WouldBlock), meaning that the API of the handshake would look like:

```rust
impl Handshake {
    fn handshake(&mut self) -> Result<Completed, Error>;
}
```

If the original question is answered, feel free to close 🙂

**Comment by hbina** [comment]
ty for the clarifications!
