### ISSUE TITLE
tungstenite-rs hides quickly sent messages

### ISSUE THREAD

**Issue by justinvreeland** [snapview/tungstenite-rs#54]
I'm new to rust so apologies if I've done something wrong and haven't noticed. 

I was using tungstenite-rs with mio and noticed that if messages were sent to quickly mio sometimes would not trigger to let me know there was a read pending. I found this confusing as I only received 1 message and multiple were sent.  After a brief debugging I found out that depending on the speed at which everything executed sometimes tungstenite-rs will read the whole contents of the stream but only return a single message, with no way of know how many remaining messages have been buffered.

There's a minimal example here:
https://github.com/justinvreeland/tungstenite-rs-issue-example

if you keep refreshing the javascript you'll see  output that from rust that looks like:

```
msg_1: Text("This is message 1")
No second message
msg_1: Text("This is message 2")
No second message
msg_1: Text("This is message 1")
msg_2: Text("This is message 2")
msg_1: Text("This is message 1")
No second message
msg_1: Text("This is message 2")
No second message
msg_1: Text("This is message 1")
No second message
msg_1: Text("This is message 2")
No second message
msg_1: Text("This is message 1")
No second message
msg_1: Text("This is message 2")
No second message

```

The behavior I'd expect is "No second message" allowing epoll to wait again, notice that there's pending data and notify again, however occasionally tungstenite-rs will read the entire contents rather than just the first message and the notification will not trigger again and we're left with a queued message.

I could read in a loop until I encounter would block or similar but It'd be nice if tungestenite-rs could either tell me how many messages it's keeping buffered or only read a single message.  Happy to take a shot at a patch if either solution seems acceptable.

**Comment by agalakhov** [comment]
While using epoll-based or other similar processing, you usually **must** read everything you get before trying to wait for more messages. Doing waiting, you claim that you have nothing else to do. Tungstenite is not an exception. It just follows an usual pattern.

If you happen to have multiple WebSocket connections and want to avoid starvation if one of the connections has a huge endless stream of messages, the correct way to do is as follows. You read a single message from Tungstenite. If there was no message, you do a blocking `epoll`. If there was one, you process it, then check quickly check for messages on your other sockets doing `epoll` with zero timeout, then continue with processing next message from partially-read socket. The one and only reason to do waiting on a socket is _a `WouldBlock` received from it_ and nothing else.

In general, it is a bad idea to do any `epoll` before you actually received a `WouldBlock`. As said above, Tungstenite is not an exception.

**Comment by justinvreeland** [comment]
That's not true. epoll puts no obligation on the user to read any amount of data from the file descriptor and neither does select or poll.  Calling epoll_wait only means that you want to be notified of new events, in level triggered mode the event is that there is data available to read from the socket. I can keep the same byte there and never read it and epoll will function perfectly fine.  In fact you can see an example of this behavior in step 3 of [this site](https://suchprogramming.com/epoll-in-3-easy-steps/).

If you don't read all of the data and call epoll_wait, assuming it's level triggered all that happens is that you'll be notified of another read event, which is the behavior that tungstenite-rs is hiding.   There's also nothing wrong with calling epoll wait before you'd get a would block.  If there's data to read it would get trigger as soon as I call epoll_wait.  What you're asserting is that I should always call any read handling code after a server accepts a new connection before waiting because the client might have sent something as soon as it connected, where common practice I've seen is to accept the connection, add it to the monitored descriptors and deal with any messages in the next iteration of wait. While there may be an argument that what you're advocating is best practices it's not required by epoll in any way.

**Comment by agalakhov** [comment]
The techniques you're described are only correct if you handle read buffers yourself. That is, you guarantee that before calling the next read you have processed the whole buffer filled with previous one.

If you are not calling `read()` yourselves, you generally don't have clear definition of what "new data" is. In a TCP connection one must not assume that one message comes in one portion of data, and many messages may come in a single portion. One can **not** tell in advance what's in the portion without reading it first. Due to performance reasons in Tungstenite we always read the portion as a whole (in a single system call).

What happens is, you can't assume that "no new data available for `read`" is the same as "no new data portions on the high-level protocol". They are the same **if and only if** you read to the end. A single `read()` call may result in more than one WebSocket message. It may also result in no messages at all if it is a control transfer or if the message is fragmented. Symmetrically, a single `write()` call may transmit more than one WebSocket message, or it may transfer less than one. You can't assume anything except that if `epoll()` is unblocked, you _probably_ get more messages. One can't tell _how many_.

> where common practice I've seen is to accept the connection, add it to the monitored descriptors and deal with any messages in the next iteration of wait
In the case of WebSocket there is a handshake stage before you can actually read messages. At this time you do not have a `WebSocket` instance. If you use `accept()` provided by Tungstenite, it does a handshake for you, and the handshake **may** be immediately followed with messages sent by the client. Here we even don't have the possibility to limit reading to the header only other than reading one byte pro syscall, since the handshake ends with "\r\n\r\n" and has no known size. This means that you may have received some messages already at the handshake stage.

**Comment by agalakhov** [comment]
Generally, you can avoid all complexities if you just use `tokio-tungstenite` instead of messing directly with `mio`. The low-level interface you're using is meant for special cases like highly optimized servers where it is usually accompanied with a sophisticated I/O scheduler on top of `mio`. If you don't need a custom scheduler, just use Tokio. It does all waiting and scheduling for you.

**Comment by justinvreeland** [comment]
I don't understand why you'd think I'm trying to avoid complexity. Only handling one message at a time greatly simplifies the code and is a common use pattern for epoll/select/poll. I'm using mio because it fits my use case. If tokio would work better I would use tokio.

The tungstenite api has a function called `read_message`  that has the description `Read a message from stream, if possible.`.  When in fact what the function does is read **all data** from the stream but only parses and returns a single message. If there's any complexity this is what's causing it.

The header in the websocket protocol provides the length of the payload.  It's not unreasonable to ask that `read_message` to either **read** only a single message, or for it to behave as one would expect `read_messages` to behave and return some kind of collection with which it could be determined how many messages were parsed and then process those.

**Comment by agalakhov** [comment]
The point is, WebSocket protocols allows multiple messages to come in a single TCP packet. As we call `read()` (we normally do it _once_), we may figure out that TCP combined multiple small messages into a single packet (which may happen exactly if you send small messages quickly). This is a desired behavior of TCP (usually there is Nagle's algorithm working).

No, Tungstenite does not read **all** data from the stream. It only reads until it finds the end of message. But it is a **buffered** read. Basically we call `read()` like this:
```
let mut buf = [0; 4096];
let size = socket.read(&mut buf)?;
```
since we do not know the size of the message in advance. Then we parse the chunk of data we got. We definitely don't want to read just the header here, since it is an extra system call and the header also has variable size, and it would be _really_ inefficient. If the buffer contains a whole message, we return it and stop reading. However, if messages are small, we may happen to have read _more than one whole message by a single `read()` call_. That is the problem you're facing, and it is not specific to Tungstenite. Every library that contains `read()` without packet size known in advance would work so. In general, never assume that there are no buffered data between the socket and the application. (Even `scanf()` and `printf()` in C work the same way.)

**Comment by justinvreeland** [comment]
I get what you're saying, and it seems I've lucked out never encountering this issue with other libraries.  But the confusion here comes from, as far as I've seen nowhere in the documentation it mentioning buffered reads, or that reading a message may in fact read more messages than the one corresponding to the payload it provides me in the message.

Yes you mention that the protocol allows for more than one message to be sent in the same tcp packet, and I appreciate the clarification but from my perspective that's not addressed in the documentation, it says it reads one message from the stream, and the stream is what I'm registering with mio to poll with so it's seems strange to me that it reads more than one message from the stream.

Thanks for your time, and clarification.
