### ISSUE TITLE
Question: Is there no buffering on write_message?

### ISSUE THREAD

**Issue by najamelan** [snapview/tungstenite-rs#68]
I try to work on correct buffering for my code, and I end up reading the code of WebSocketContext::write_message. Maybe I'm missing something, but the docs say:

`/// WebSocket will buffer a configurable number of messages at a time, ...`

However there is only one call to `self.send_queue.push_back(frame)` at the end of the method:
```rust
self.send_queue.push_back(frame);
self.write_pending(stream)
```
as you can see it's immediately followed by `self.write_pending(stream)`. When looking at `write_pending` it does seem that it tries to send all messages out, even if the queue is not full. 

So I wonder, does every message immediately get flushed? If so that seems contradictory to the documentation.

**Comment by agalakhov** [comment]
It _tries_ to send every message immediately if the network connection is ready for sending. If not, message is kept in the buffer. The maximum number of buffered messages is configurable so that the buffer does not grow infinitely. After hitting the limit Tungstenite will refuse to accept messages until queued messages are sent.

**Comment by najamelan** [comment]
OK, that makes sense. Thanks for clarifying. To sum up what I understand:

1. There is no implicit buffering that needs to be flushed
2. There is back pressure.

**Comment by agalakhov** [comment]
Correct.
