### ISSUE TITLE
Allow invalid tls certs?

### ISSUE THREAD

**Issue by yusefkarim** [snapview/tungstenite-rs#84]
Hey,

I know you probably don't want to let users do this, but would you possibly be interested in optionally letting the user accept invalid certs when connecting?

I have used:
```
let connector = TlsConnector::builder().danger_accept_invalid_certs(true).build()?;
```
Instead of:
```
let connector = TlsConnector::builder().build()?;
```
In the tls encryption module (client.rs). This allows me to connect to my websocket server while I test without having to worry about setting up certificates.

**Comment by agalakhov** [comment]
There is `client()` function which allows for using already established connections. You may use this to upgrade an already established connection to WebSocket. The certificate check will then reside in your code.

**Comment by yusefkarim** [comment]
Sorry, I did not see that method! Here is my big ugly function that got everything I mentioned working:
```
  pub async fn wait_for_websocket_connection(host: &str, port: u32) -> WebSocket<TlsStream<TcpStream>> {    
      let config = Some(WebSocketConfig { max_send_queue: None,    
                                          max_message_size: None,    
                                          max_frame_size: None });    
      let connector = TlsConnector::builder()    
                                    .danger_accept_invalid_certs(true)    
                                    .build().unwrap();    
      
      loop {                                                                                                                                                                  
          let stream = TcpStream::connect(format!("{}:{}", host, port)).unwrap();    
          let tls_stream = connector.connect(host, stream).unwrap();                 
          let parsed_url = Url::parse(&format!("wss://{}:{}",host, port)).unwrap();    
                                                                                       
          if let Ok(socket_connection) = client_with_config(parsed_url,                
                                                            tls_stream,                
                                                            config)                    
          {                                                                
              log::info!("Websocket connected to {}", format!("{}:{}", host, port));    
              return socket_connection.0;                                               
          } else {                                                                      
              log::warn!("Websocket connection error, trying again...");                
              sleep(Duration::from_secs(5));                                            
          }                                                                 
      }                                                                     
  }
```
Thank you for your response, if you would like I can try to clean up the code above and add an example to your examples section? If not, feel free to close this issue, thank you.

**Comment by application-developer-DA** [comment]
Current state for those who may have the similar issue: at the moment we don't have plans / tracking issue to implement the `danger_accept_invalid_certs()` in the near future. Strictly speaking it does not have anything to do with the WebSockets and is not a purpose of this particular crate to abstract the TLS options. Even the `connect()` function is currently nothing but a helper / an optional feature that was introduced by us since connecting to the WSS on the client side to the server is quite a common thing nowadays.

The users that need to fine tune the TLS behavior (those who need something non-trivial or more specific) can and should do the corresponding changes in the TLS stream (or in fact any other compatible stream) and pass it to on of the `client()` functions that the `tungstenite-rs` exposes (any `Read + Write` stream would do). We can't expose every possible TLS option and abstract it for the end user as that would be mixing the responsibilities of this crate with some sort of the TLS helper and would need to either expose a sophisticated and not user friendly config and/or hide many **important** details that define which root certificate store is used / which certificates are allowed etc.

We currently support 2 different implementations for the TLS and 2 ways to provide different root certificates to it. So making an additional layer of abstraction for `danger_accept_invalid_certs()` would entail adding options for other similar things like `danger_accept_invalid_hostnames()` etc and generally may make usage of the library even more confusing and less obvious considering the different TLS features and flexibility that we already provide (though we would ofc review the incoming PR if some good and elegant solution is found). The things that may make much more sense though are e.g. https://github.com/snapview/tungstenite-rs/issues/203 and similar issues. However the one can see that using it like this won't be too much different from the solution that has been posted in this issue and generally speaking will still involve some actions from the user / creating the config, i.e. the general idea is that it's only the user who knows own needs w.r.t. TLS and we should not and do not want to really dictate the ways how the one or another should use TLS as it's up to the application to decide and not the purpose of this crate.

So the current plan and agenda is to continue with the changes like this one https://github.com/snapview/tungstenite-rs/pull/217 and related TLS features for very common things that to spare some boilerplate in typical scenarios.

As mentioned above there is always a possibility to implement any behavior the user wants including the one that is being discussed here and doing so with `danger_accept_invalid_certs()` thing which would require the user to write another 5-8 LOC in the application, passing the resulting stream to the `tungstenite-rs`'s [`client()` function](https://docs.rs/tungstenite/0.14.0/tungstenite/client/fn.client.html).
